#!/usr/bin/env python3
"""expand_stores.py — Expande retailers a ~1000 aplicando patrones por país sobre VTEX."""

import csv
from pathlib import Path

CURRENCIES = {
    "PE":"PEN","AR":"ARS","BR":"BRL","MX":"MXN","CO":"COP","CL":"CLP","ES":"EUR","FR":"EUR","IT":"EUR","DE":"EUR","GB":"GBP","PT":"EUR","NL":"EUR","BE":"EUR","PL":"PLN","SE":"SEK","DK":"DKK","FI":"EUR","NO":"NOK","AT":"EUR","CH":"CHF","IE":"EUR","GR":"EUR","CZ":"CZK","RO":"RON","HU":"HUF","SK":"EUR","BG":"BGN","HR":"EUR","SI":"EUR","UY":"UYU","EC":"USD","BO":"BOB","PY":"PYG","VE":"USD","CR":"CRC","GT":"GTQ","SV":"USD","PA":"USD","DO":"DOP","US":"USD","CA":"CAD","AU":"AUD","NZ":"NZD","JP":"JPY","KR":"KRW","CN":"CNY","TW":"TWD","HK":"HKD","SG":"SGD","TH":"THB","IN":"INR","MY":"MYR","ID":"IDR","TR":"TRY","ZA":"ZAR","AE":"AED","SA":"SAR","RU":"RUB",
}

PATTERNS = [
    ("Carrefour {cc}", "carrefour.{domain}", "supermercados", {"AR":"com.ar","BR":"com.br","ES":"es","FR":"fr","IT":"it","BE":"be","RO":"ro","PL":"pl"}),
    ("Lider {cc}", "lider.{domain}", "supermercados", {"CL":"cl"}),
    ("Santa Isabel {cc}", "santaisabel.{domain}", "supermercados", {"CL":"cl","PE":"pe"}),
    ("Cencosud {cc}", "cencosud.{domain}", "supermercados", {"AR":"com.ar","CL":"cl","PE":"pe","CO":"co","BR":"com.br","UY":"uy"}),
    ("Dia {cc}", "dia.{domain}", "supermercados", {"AR":"com.ar","BR":"com.br","ES":"es","PT":"pt"}),
    ("Walmart {cc}", "walmart.{domain}", "supermercados", {"MX":"com.mx","CL":"cl","AR":"com.ar","US":"com"}),
    ("Éxito {cc}", "exito.{domain}", "supermercados", {"CO":"com","UY":"uy","EC":"ec"}),
    ("Sodimac {cc}", "sodimac.{domain}", "hogar", {"CO":"com.co","CL":"cl","PE":"pe","AR":"com.ar","BR":"com.br","MX":"com.mx","UY":"com.uy"}),
    ("Easy {cc}", "easy.{domain}", "hogar", {"AR":"com.ar","CL":"cl","CO":"co","PE":"pe"}),
    ("Ripley {cc}", "ripley.{domain}", "departamentales", {"CL":"cl","PE":"pe","CO":"co","MX":"com.mx","AR":"com.ar"}),
    ("Falabella {cc}", "falabella.{domain}", "departamentales", {"CL":"cl","PE":"pe","CO":"co","AR":"com.ar","BR":"com.br","MX":"com.mx","UY":"com.uy"}),
    ("Samsung {cc}", "samsung.{domain}", "electro", {"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","PE":"pe","CO":"co","ES":"es","FR":"fr","IT":"it","GB":"uk","DE":"de","US":"us","PT":"pt"}),
    ("LG {cc}", "lg.{domain}", "electro", {"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","ES":"es","FR":"fr","IT":"it","DE":"de","US":"us","PT":"pt"}),
    ("Motorola {cc}", "motorola.{domain}", "electro", {"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","ES":"es","IT":"it","GB":"co.uk","DE":"de","US":"com"}),
    ("Electrolux {cc}", "electrolux.{domain}", "electro", {"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","ES":"es","IT":"it","FR":"fr","DE":"de","SE":"se","PT":"pt","NL":"nl"}),
    ("Whirlpool {cc}", "whirlpool.{domain}", "electro", {"BR":"com.br","MX":"com.mx","AR":"com.ar","ES":"es","IT":"it","FR":"fr","DE":"de","GB":"co.uk","US":"com","PT":"pt"}),
    ("C&A {cc}", "cea.{domain}", "moda", {"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","PE":"pe","CO":"co","ES":"es","FR":"fr","DE":"de","IT":"it","PT":"pt","NL":"nl"}),
    ("Hering {cc}", "hering.{domain}", "moda", {"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","PE":"pe","CO":"co"}),
    ("Zara {cc}", "zara.{domain}", "moda", {"ES":"es","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt","NL":"nl","CL":"cl","MX":"com.mx","AR":"com.ar","CO":"co","PE":"pe","BR":"com.br"}),
    ("Mango {cc}", "mango.{domain}", "moda", {"ES":"com","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt","NL":"nl"}),
    ("Decathlon {cc}", "decathlon.{domain}", "deportes", {"FR":"fr","ES":"es","IT":"it","DE":"de","GB":"co.uk","PT":"pt","NL":"nl","BE":"be","PL":"pl","BR":"com.br","CL":"cl","PE":"pe","CO":"com.co","AR":"com.ar","MX":"com.mx","SE":"se"}),
    ("Nike {cc}", "nike.{domain}", "deportes", {"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","PE":"pe","CO":"co","ES":"es","FR":"fr","IT":"it","DE":"de","GB":"com","PT":"pt","NL":"nl","SE":"se","PL":"pl"}),
    ("Adidas {cc}", "adidas.{domain}", "deportes", {"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","PE":"pe","CO":"co","ES":"es","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt","NL":"nl","PL":"pl","SE":"se"}),
    ("Puma {cc}", "puma.{domain}", "deportes", {"BR":"com.br","MX":"com.mx","AR":"com.ar","ES":"es","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt","NL":"nl"}),
    ("O Boticário {cc}", "oboticario.{domain}", "belleza", {"BR":"com.br","PT":"pt","AR":"com.ar","CL":"cl","PE":"pe","CO":"co","MX":"com.mx","BO":"com.bo","PY":"com.py","UY":"com.uy","ES":"es","FR":"fr","IT":"it","DE":"de","GB":"co.uk","US":"com"}),
    ("Natura {cc}", "natura.{domain}", "belleza", {"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","PE":"pe","CO":"co","BO":"com.bo","FR":"fr"}),
    ("Avon {cc}", "avon.{domain}", "belleza", {"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","ES":"es","FR":"fr","IT":"it","DE":"de","GB":"com","PT":"pt","PL":"pl"}),
    ("Leroy Merlin {cc}", "leroymerlin.{domain}", "hogar", {"BR":"com.br","ES":"es","FR":"fr","IT":"it","PT":"pt","PL":"pl","RO":"ro"}),
    ("Rosen {cc}", "rosen.{domain}", "hogar", {"CL":"cl","PE":"pe","CO":"co","MX":"com.mx","AR":"com.ar","EC":"com"}),
    ("Nestlé {cc}", "nestle.{domain}", "alimentos", {"BR":"com.br","MX":"com.mx","AR":"com.ar","ES":"es","FR":"fr","IT":"it","DE":"de","PT":"pt","CL":"cl","CO":"co","PE":"pe","GB":"co.uk"}),
    ("Unilever {cc}", "unilever.{domain}", "alimentos", {"BR":"com.br","MX":"com.mx","AR":"com.ar","ES":"es","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt","NL":"nl"}),
    ("Danone {cc}", "danone.{domain}", "alimentos", {"BR":"com.br","MX":"com.mx","AR":"com.ar","ES":"es","FR":"fr","IT":"it","DE":"de","PT":"pt"}),
    ("Leonisa {cc}", "leonisa.{domain}", "moda", {"CO":"com","PE":"pe","MX":"com.mx","ES":"es","US":"com"}),
    ("Totto {cc}", "totto.{domain}", "moda", {"CO":"com","PE":"pe","EC":"com","MX":"com.mx","CR":"co.cr","GT":"com.gt","PA":"com.pa","BO":"com.bo"}),
    ("Farmatodo {cc}", "farmatodo.{domain}", "farmacias", {"CO":"com.co","MX":"com.mx","VE":"com.ve","AR":"com.ar"}),
    ("Cruz Verde {cc}", "cruzverde.{domain}", "farmacias", {"CO":"com.co","CL":"cl","PE":"pe","MX":"com.mx"}),
    ("Office Depot {cc}", "officedepot.{domain}", "libreria", {"MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","US":"com","PE":"pe"}),
    ("H&M {cc}", "hm.{domain}", "moda", {"ES":"es","FR":"fr","IT":"it","DE":"de","GB":"com","PT":"pt","NL":"nl","CL":"cl","MX":"com.mx","AR":"com.ar","PE":"pe","CO":"co","BR":"com.br"}),
    ("Farmacias Guadalajara {cc}", "farmaciasguadalajara.{domain}", "farmacias", {"MX":"com.mx"}),
    ("Farmacias del Ahorro {cc}", "farmaciasdelahorro.{domain}", "farmacias", {"MX":"com.mx"}),
    ("Coppel {cc}", "coppel.{domain}", "departamentales", {"MX":"com","AR":"com.ar"}),
    ("Garbarino {cc}", "garbarino.{domain}", "electro", {"AR":"com.ar"}),
    ("MediaMarkt {cc}", "mediamarkt.{domain}", "electro", {"ES":"es","DE":"de","IT":"it","NL":"nl","PL":"pl","PT":"pt","AT":"at"}),
    ("AutoZone {cc}", "autozone.{domain}", "autopartes", {"MX":"com.mx","US":"com","BR":"com.br"}),
    ("Swift {cc}", "swift.{domain}", "alimentos", {"BR":"com.br","AR":"com.ar","UY":"com.uy"}),
    ("Petlove {cc}", "petlove.{domain}", "mascotas", {"BR":"com.br"}),
    ("Petz {cc}", "petz.{domain}", "mascotas", {"BR":"com.br"}),
    ("Cobasi {cc}", "cobasi.{domain}", "mascotas", {"BR":"com.br"}),
    ("Saraiva {cc}", "saraiva.{domain}", "libreria", {"BR":"com.br"}),
    ("Livraria Cultura {cc}", "livrariacultura.{domain}", "libreria", {"BR":"com.br"}),
    ("Centauro {cc}", "centauro.{domain}", "deportes", {"BR":"com.br"}),
    ("Casas Bahia {cc}", "casasbahia.{domain}", "electro", {"BR":"com.br"}),
    ("Ponto Frio {cc}", "pontofrio.{domain}", "electro", {"BR":"com.br"}),
    ("Marisa {cc}", "marisa.{domain}", "moda", {"BR":"com.br","AR":"com.ar"}),
    ("Riachuelo {cc}", "riachuelo.{domain}", "moda", {"BR":"com.br"}),
    ("Magazine Luiza {cc}", "magazineluiza.{domain}", "electro", {"BR":"com.br"}),
]

KEY_MAP = {
    " ":"_",".":"",",":"","'":"","’":"","(":"",")":"","&":"","+":"","!":"","?":"","/":"","\\":"","\u00e1":"a","\u00e9":"e","\u00ed":"i","\u00f3":"o","\u00fa":"u","\u00f1":"n","\u00e4":"a","\u00eb":"e","\u00ef":"i","\u00f6":"o","\u00fc":"u","\u00e0":"a","\u00e8":"e","\u00ec":"i","\u00f2":"o","\u00f9":"u","\u00e2":"a","\u00ea":"e","\u00ee":"i","\u00f4":"o","\u00fb":"u"
}

def make_key(name, cc):
    name_clean = "".join(KEY_MAP.get(c, c) for c in name.lower()).replace("__","_").strip("_")
    return f"{name_clean}_{cc.lower()}"

SCORE = "5,5,4,3,5"

def main():
    existing = set()
    if Path("stores_curated.csv").exists():
        with open("stores_curated.csv", newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                existing.add(row["key"])

    new_rows = []
    for name_tpl, base_tpl, line, countries in PATTERNS:
        for cc, domain in countries.items():
            name = name_tpl.replace("{cc}", cc)
            key = make_key(name, cc)
            base = f"https://www.{base_tpl.replace('{domain}', domain)}"
            currency = CURRENCIES.get(cc, "USD")
            if key not in existing:
                new_rows.append(f"{key},{name},{base},{cc},{currency},{line},{SCORE}")
                existing.add(key)

    with open("stores_curated.csv", "a", newline="", encoding="utf-8") as f:
        for row in new_rows:
            f.write(row + "\n")

    print(f"Added {len(new_rows)} new retailers to CSV")

PATTERNS += [
    ("Sephora {cc}","sephora.{domain}","belleza",{"BR":"com.br","MX":"com.mx","ES":"es","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt"}),
    ("MAC {cc}","maccosmetics.{domain}","belleza",{"BR":"com.br","MX":"com.mx","AR":"com.ar","ES":"es","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt"}),
    ("IKEA {cc}","ikea.{domain}","hogar",{"ES":"es","FR":"fr","IT":"it","DE":"de","GB":"com","PT":"pt","NL":"nl","BE":"be","PL":"pl"}),
    ("Lidl {cc}","lidl.{domain}","supermercados",{"DE":"de","ES":"es","FR":"fr","IT":"it","GB":"co.uk","PT":"pt","NL":"nl","BE":"be","PL":"pl"}),
    ("Aldi {cc}","aldi.{domain}","supermercados",{"DE":"de","US":"us","GB":"co.uk","FR":"fr","ES":"es","IT":"it","NL":"nl"}),
    ("Tesco {cc}","tesco.{domain}","supermercados",{"GB":"com","IE":"ie","PL":"pl","CZ":"cz","SK":"sk","HU":"hu"}),
    ("Dafiti {cc}","dafiti.{domain}","moda",{"BR":"com.br","MX":"com.mx","AR":"com.ar","CL":"cl","CO":"co","PE":"pe"}),
    ("Mobly {cc}","mobly.{domain}","hogar",{"BR":"com.br"}),
    ("Netshoes {cc}","netshoes.{domain}","deportes",{"BR":"com.br"}),
    ("Converse {cc}","converse.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au","JP":"jp","KR":"kr"}),
    ("Vans {cc}","vans.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au","JP":"jp"}),
    ("Skechers {cc}","skechers.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au"}),
    ("Crocs {cc}","crocs.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in"}),
    ("Fila {cc}","fila.{domain}","deportes",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg"}),
    ("Reebok {cc}","reebok.{domain}","deportes",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in"}),
    ("Calvin Klein {cc}","calvinklein.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl"}),
    ("Tommy Hilfiger {cc}","tommy.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au"}),
    ("Lacoste {cc}","lacoste.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr"}),
    ("Columbia {cc}","columbia.{domain}","deportes",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au","JP":"jp","KR":"kr"}),
    ("The North Face {cc}","thenorthface.{domain}","deportes",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Forever 21 {cc}","forever21.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","SE":"se","DK":"dk","FI":"fi","NO":"no","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","ZA":"co.za","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Levis {cc}","levis.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","SE":"se","DK":"dk","FI":"fi","NO":"no","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"com.tr","ZA":"co.za","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg"}),
    ("Asics {cc}","asics.{domain}","deportes",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Timberland {cc}","timberland.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr","AU":"com.au"}),
    ("Gap {cc}","gap.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","CL":"cl","AR":"com.ar","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","SE":"se","DK":"dk","FI":"fi","NO":"no","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"com.tr","ZA":"co.za","AU":"com.au","JP":"jp","CN":"cn","SG":"sg"}),
    ("Guess {cc}","guess.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","TR":"com.tr"}),
    ("Diesel {cc}","diesel.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl"}),
    ("Pandora {cc}","pandora.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","AT":"at","AU":"com.au"}),
    ("Swatch {cc}","swatch.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","CH":"ch","AT":"at"}),
    ("Bose {cc}","bose.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au"}),
    ("Sony {cc}","sony.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","SE":"se","DK":"dk","FI":"fi","NO":"no","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"com.tr","ZA":"co.za","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg"}),
    ("Philips {cc}","philips.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","AT":"at","AU":"com.au"}),
    ("Dell {cc}","dell.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","AT":"at","AU":"com.au","JP":"jp","CN":"cn","IN":"in"}),
    ("HP {cc}","hp.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","PL":"pl","AT":"at","AU":"com.au","JP":"jp","CN":"cn","IN":"in"}),
    ("Apple {cc}","apple.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg"}),
    ("Microsoft {cc}","microsoft.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in"}),
    ("Canon {cc}","canon.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp"}),
    ("Nikon {cc}","nikon.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp"}),
    ("JBL {cc}","jbl.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au"}),
    ("GoPro {cc}","gopro.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au"}),
    ("Huawei {cc}","huawei.{domain}","electro",{"MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","CL":"cl","AR":"com.ar","PE":"pe","CO":"co"}),
    ("Xiaomi {cc}","xiaomi.{domain}","electro",{"MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","CL":"cl","AR":"com.ar","PE":"pe","CO":"co","IN":"in","SG":"sg","MY":"my","TH":"th","ID":"id","TR":"tr","RU":"ru","PL":"pl","CZ":"cz","GR":"gr","RO":"ro","HU":"hu","AU":"com.au"}),
    ("Lenovo {cc}","lenovo.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in"}),
    ("Acer {cc}","acer.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","IN":"in"}),
    ("Asus {cc}","asus.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","IN":"in"}),
    ("Logitech {cc}","logitech.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au"}),
    ("Razer {cc}","razer.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr"}),
    ("Uniqlo {cc}","uniqlo.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","SE":"se","DK":"dk","FI":"fi","NO":"no","AT":"at","CH":"ch","IE":"ie","TR":"tr","RU":"ru","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg","MY":"my","TH":"th","ID":"id","PH":"ph","VN":"vn"}),
    ("Massimo Dutti {cc}","massimodutti.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"tr","RU":"ru","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Pull&Bear {cc}","pullbear.{domain}","moda",{"US":"com","MX":"com.mx","ES":"com","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"tr","RU":"ru","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Bershka {cc}","bershka.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"tr","RU":"ru","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Stradivarius {cc}","stradivarius.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"tr","RU":"ru","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Kiehl's {cc}","kiehls.{domain}","belleza",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Clinique {cc}","clinique.{domain}","belleza",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Estee Lauder {cc}","esteelauder.{domain}","belleza",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Lancome {cc}","lancome.{domain}","belleza",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Yves Rocher {cc}","yves-rocher.{domain}","belleza",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","RU":"ru","TR":"tr","CZ":"cz","RO":"ro","HU":"hu"}),
    ("Foot Locker {cc}","footlocker.{domain}","deportes",{"US":"com","MX":"com.mx","CA":"ca","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"tr","AU":"com.au","NZ":"nz","JP":"jp","KR":"kr","HK":"hk","SG":"sg"}),
    ("JD Sports {cc}","jdsports.{domain}","deportes",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"tr","AU":"com.au","NZ":"nz"}),
    ("Intersport {cc}","intersport.{domain}","deportes",{"ES":"es","FR":"fr","DE":"de","IT":"it","PT":"pt","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"tr","FI":"fi","NO":"no","SE":"se","DK":"dk","NL":"nl","BE":"be","PL":"pl"}),
    ("Tous {cc}","tous.{domain}","moda",{"US":"com","MX":"com.mx","ES":"com","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","RU":"ru","JP":"jp","KR":"kr","CN":"cn"}),
    ("Claire's {cc}","claires.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie","TR":"tr","AU":"com.au"}),
    ("Accessorize {cc}","accessorize.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie","TR":"tr","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg","MY":"my"}),
    ("Miniso {cc}","miniso.{domain}","departamentales",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg","MY":"my","TH":"th","ID":"id","PH":"ph","VN":"vn","TR":"tr","RU":"ru"}),
    ("DM {cc}","dm.{domain}","farmacias",{"DE":"de","AT":"at","CZ":"cz","SK":"sk","HU":"hu","RO":"ro","BG":"bg","HR":"hr","SI":"si","IT":"it"}),
    ("Rossmann {cc}","rossmann.{domain}","farmacias",{"DE":"de","PL":"pl","CZ":"cz","HU":"hu","TR":"tr"}),
    ("Mercado Libre {cc}","mercadolibre.{domain}","departamentales",{"AR":"com.ar","BR":"com.br","MX":"com.mx","CO":"co","CL":"cl","PE":"pe","UY":"com.uy","VE":"ve","EC":"ec","CR":"cr","GT":"gt","PA":"pa","DO":"do","BO":"bo","PY":"py","SV":"sv","NI":"ni","HN":"hn"}),
    ("Americanas {cc}","americanas.{domain}","departamentales",{"BR":"com.br"}),
    ("Kabum {cc}","kabum.{domain}","electro",{"BR":"com.br"}),
    ("Fast Shop {cc}","fastshop.{domain}","electro",{"BR":"com.br"}),
    ("Pernambucanas {cc}","pernambucanas.{domain}","departamentales",{"BR":"com.br"}),
    ("Havan {cc}","havan.{domain}","departamentales",{"BR":"com.br"}),
    ("Polishop {cc}","polishop.{domain}","hogar",{"BR":"com.br","MX":"com.mx","CL":"cl","PE":"pe","CO":"co","AR":"com.ar"}),
    ("Camicado {cc}","camicado.{domain}","hogar",{"BR":"com.br"}),
    ("Tottus {cc}","tottus.{domain}","supermercados",{"PE":"pe","CL":"cl","AR":"com.ar"}),
    ("Makro {cc}","makro.{domain}","supermercados",{"PE":"pe","CL":"cl","AR":"com.ar","BR":"com.br","CO":"co","VE":"ve","EC":"ec","BO":"bo","PY":"py","UY":"uy","NL":"nl","BE":"be","ES":"es","PT":"pt","GB":"co.uk","PL":"pl","CZ":"cz"}),
    ("Costco {cc}","costco.{domain}","supermercados",{"US":"com","MX":"com.mx","CA":"ca","GB":"co.uk","ES":"es","FR":"fr","JP":"jp","KR":"kr","TW":"tw","AU":"com.au","NZ":"nz"}),
    ("Sam's Club {cc}","samsclub.{domain}","supermercados",{"US":"com","MX":"com.mx","BR":"com.br","CN":"cn"}),
    ("Kroger {cc}","kroger.{domain}","supermercados",{"US":"com"}),
    ("Safeway {cc}","safeway.{domain}","supermercados",{"US":"com","GB":"co.uk","CA":"ca","AU":"com.au"}),
    ("Whole Foods {cc}","wholefoodsmarket.{domain}","supermercados",{"US":"com","CA":"ca","GB":"co.uk"}),
    ("Trader Joe's {cc}","traderjoes.{domain}","supermercados",{"US":"com"}),
    ("Publix {cc}","publix.{domain}","supermercados",{"US":"com"}),
    # Batch 4 — massive expansion for 3400 target
    ("Albert Heijn {cc}","ah.{domain}","supermercados",{"NL":"nl","BE":"be"}),
    ("Coles {cc}","coles.{domain}","supermercados",{"AU":"com.au"}),
    ("Woolworths {cc}","woolworths.{domain}","supermercados",{"AU":"com.au","NZ":"co.nz"}),
    ("Sainsburys {cc}","sainsburys.{domain}","supermercados",{"GB":"co.uk","IE":"ie"}),
    ("Morrisons {cc}","morrisons.{domain}","supermercados",{"GB":"com"}),
    ("Asda {cc}","asda.{domain}","supermercados",{"GB":"com"}),
    ("Waitrose {cc}","waitrose.{domain}","supermercados",{"GB":"com"}),
    ("Marks & Spencer {cc}","marksandspencer.{domain}","supermercados",{"GB":"com","IE":"ie","IN":"in","SG":"sg","MY":"my","HK":"hk"}),
    ("Edeka {cc}","edeka.{domain}","supermercados",{"DE":"de"}),
    ("Rewe {cc}","rewe.{domain}","supermercados",{"DE":"de","AT":"at"}),
    ("Penny {cc}","penny.{domain}","supermercados",{"DE":"de","AT":"at","CZ":"cz","HU":"hu","IT":"it","RO":"ro"}),
    ("Kaufland {cc}","kaufland.{domain}","supermercados",{"DE":"de","PL":"pl","CZ":"cz","SK":"sk","RO":"ro","BG":"bg","HR":"hr"}),
    ("Biedronka {cc}","biedronka.{domain}","supermercados",{"PL":"pl"}),
    ("Zabka {cc}","zabka.{domain}","supermercados",{"PL":"pl","CZ":"cz"}),
    ("El Corte Ingles {cc}","elcorteingles.{domain}","departamentales",{"ES":"es","PT":"pt"}),
    ("Boots {cc}","boots.{domain}","farmacias",{"GB":"com","IE":"ie","TH":"th","NO":"no"}),
    ("Superdrug {cc}","superdrug.{domain}","farmacias",{"GB":"com","IE":"ie"}),
    ("Muller {cc}","mueller.{domain}","farmacias",{"DE":"de","AT":"at","CH":"ch","HR":"hr","SI":"si","HU":"hu"}),
    ("Normal {cc}","normal.{domain}","farmacias",{"DK":"dk","SE":"se","NO":"no","FI":"fi","NL":"nl","FR":"fr","PT":"pt","ES":"es"}),
    ("Coolblue {cc}","coolblue.{domain}","electro",{"NL":"nl","BE":"be","DE":"de"}),
    ("Bol {cc}","bol.{domain}","departamentales",{"NL":"com","BE":"com"}),
    ("Otto {cc}","otto.{domain}","departamentales",{"DE":"de","AT":"at","CH":"ch","NL":"nl","FR":"fr","ES":"es","IT":"it","PL":"pl","CZ":"cz","RU":"ru","BR":"com.br"}),
    ("Emag {cc}","emag.{domain}","electro",{"RO":"ro","BG":"bg","HU":"hu","PL":"pl","CZ":"cz","SK":"sk"}),
    ("Alza {cc}","alza.{domain}","electro",{"CZ":"cz","SK":"sk","HU":"hu","AT":"at","DE":"de","GB":"co.uk"}),
    ("Allegro {cc}","allegro.{domain}","departamentales",{"PL":"pl","CZ":"cz","SK":"sk"}),
    ("Submarino {cc}","submarino.{domain}","departamentales",{"BR":"com.br"}),
    ("Shoptime {cc}","shoptime.{domain}","electro",{"BR":"com.br"}),
    ("Ricardo Eletro {cc}","ricardoeletro.{domain}","electro",{"BR":"com.br"}),
    ("Le Biscuit {cc}","lebiscuit.{domain}","departamentales",{"BR":"com.br"}),
    ("Carrefour Express {cc}","carrefour.{domain}","supermercados",{"AR":"com.ar","BR":"com.br","ES":"es","FR":"fr","IT":"it","BE":"be","RO":"ro","PL":"pl"}),
    ("E.Leclerc {cc}","leclerc.{domain}","supermercados",{"FR":"fr","ES":"es","PT":"pt","PL":"pl"}),
    ("Monoprix {cc}","monoprix.{domain}","supermercados",{"FR":"fr"}),
    ("Franprix {cc}","franprix.{domain}","supermercados",{"FR":"fr"}),
    ("Super U {cc}","superu.{domain}","supermercados",{"FR":"fr"}),
    ("Cora {cc}","cora.{domain}","supermercados",{"FR":"fr","BE":"be","LU":"lu","RO":"ro"}),
    ("Delhaize {cc}","delhaize.{domain}","supermercados",{"BE":"be","LU":"lu"}),
    ("Colruyt {cc}","colruyt.{domain}","supermercados",{"BE":"be","FR":"fr","LU":"lu"}),
    ("Esselunga {cc}","esselunga.{domain}","supermercados",{"IT":"it"}),
    ("Conad {cc}","conad.{domain}","supermercados",{"IT":"it"}),
    ("Coop {cc}","coop.{domain}","supermercados",{"IT":"it","CH":"ch","DK":"dk","SE":"se","NO":"no","FI":"fi"}),
    ("Billa {cc}","billa.{domain}","supermercados",{"AT":"at","CZ":"cz","SK":"sk","BG":"bg","RU":"ru"}),
    ("Netto {cc}","netto.{domain}","supermercados",{"DE":"de","DK":"dk","SE":"se","PL":"pl"}),
    ("ICA {cc}","ica.{domain}","supermercados",{"SE":"se","NO":"no","FI":"fi","EE":"ee","LV":"lv","LT":"lt"}),
    ("Kesko {cc}","kesko.{domain}","supermercados",{"FI":"fi","SE":"se","NO":"no","EE":"ee","LV":"lv","LT":"lt","PL":"pl"}),
    ("Rimi {cc}","rimi.{domain}","supermercados",{"LV":"lv","LT":"lt","EE":"ee"}),
    ("Maxima {cc}","maxima.{domain}","supermercados",{"LT":"lt","LV":"lv","EE":"ee","BG":"bg","PL":"pl"}),
    ("La Comer {cc}","lacomer.{domain}","supermercados",{"MX":"com.mx"}),
    ("City Market {cc}","citymarket.{domain}","supermercados",{"MX":"com.mx"}),
    ("Fresko {cc}","fresko.{domain}","supermercados",{"MX":"com.mx"}),
    ("Sumesa {cc}","sumesa.{domain}","supermercados",{"MX":"com.mx"}),
    ("Superama {cc}","superama.{domain}","supermercados",{"MX":"com.mx"}),
    ("Bodega Aurrera {cc}","bodegaaurrera.{domain}","supermercados",{"MX":"com.mx"}),
    ("Mi Bodega Aurrera {cc}","mibodegaaurrera.{domain}","supermercados",{"MX":"com.mx"}),
    ("Galeries Lafayette {cc}","galerieslafayette.{domain}","departamentales",{"FR":"com"}),
    ("Printemps {cc}","printemps.{domain}","departamentales",{"FR":"com"}),
    ("Selfridges {cc}","selfridges.{domain}","departamentales",{"GB":"com"}),
    ("Harrods {cc}","harrods.{domain}","departamentales",{"GB":"com"}),
    ("Westwing {cc}","westwing.{domain}","hogar",{"DE":"de","ES":"es","FR":"fr","IT":"it","NL":"nl","AT":"at","CH":"ch","CZ":"cz","PL":"pl","RO":"ro","SK":"sk","BR":"com.br"}),
    ("Wayfair {cc}","wayfair.{domain}","hogar",{"US":"com","CA":"ca","GB":"co.uk","DE":"de","IE":"ie","AT":"at"}),
    ("Home24 {cc}","home24.{domain}","hogar",{"DE":"de","FR":"fr","AT":"at","CH":"ch","NL":"nl","BE":"be","IT":"it","BR":"com.br"}),
    ("AO {cc}","ao.{domain}","electro",{"GB":"com","DE":"de","NL":"nl"}),
    ("PriceSmart {cc}","pricesmart.{domain}","supermercados",{"US":"com","MX":"com.mx","CR":"cr","GT":"gt","SV":"sv","PA":"pa","DO":"do","CO":"co","PE":"pe","CL":"cl","AR":"ar","BR":"br","HN":"hn","NI":"ni"}),
    ("Whole Foods {cc}","wholefoodsmarket.{domain}","supermercados",{"US":"com","CA":"ca","GB":"co.uk"}),
    ("Food Lion {cc}","foodlion.{domain}","supermercados",{"US":"com"}),
    ("Giant Eagle {cc}","gianteagle.{domain}","supermercados",{"US":"com"}),
    ("Meijer {cc}","meijer.{domain}","supermercados",{"US":"com"}),
    ("Hy-Vee {cc}","hy-vee.{domain}","supermercados",{"US":"com"}),
    ("ShopRite {cc}","shoprite.{domain}","supermercados",{"US":"com","ZA":"co.za","NG":"ng"}),
    ("Stop & Shop {cc}","stopandshop.{domain}","supermercados",{"US":"com"}),
    ("Giant Food {cc}","giantfood.{domain}","supermercados",{"US":"com"}),
    ("Winn-Dixie {cc}","winndixie.{domain}","supermercados",{"US":"com"}),
    ("Wegmans {cc}","wegmans.{domain}","supermercados",{"US":"com"}),
    ("Muji {cc}","muji.{domain}","hogar",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","TH":"th"}),
    ("Flying Tiger {cc}","flyingtiger.{domain}","hogar",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"tr","AU":"com.au","JP":"jp","KR":"kr"}),
    ("Pier 1 {cc}","pier1.{domain}","hogar",{"US":"com","MX":"com.mx"}),
    ("Oysho {cc}","oysho.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie","TR":"tr","RU":"ru","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Zara Home {cc}","zarahome.{domain}","hogar",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch"}),
    ("Rituals {cc}","rituals.{domain}","belleza",{"US":"com","MX":"com","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie"}),
    ("Sports Direct {cc}","sportsdirect.{domain}","deportes",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"com","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","IE":"ie","GR":"gr","CZ":"cz","RO":"ro","HU":"hu","TR":"tr","AU":"com.au"}),
    ("XXL Sport {cc}","xxl.{domain}","deportes",{"SE":"se","NO":"no","FI":"fi","DK":"dk","AT":"at","DE":"de"}),
    ("BenQ {cc}","benq.{domain}","electro",{"US":"com","MX":"com.mx","DE":"de","ES":"es","FR":"fr","GB":"co.uk","IT":"it","NL":"nl","AU":"com.au"}),
    ("Fossil {cc}","fossil.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","CN":"cn","IN":"in","SG":"sg"}),
    ("Michael Kors {cc}","michaelkors.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Coach {cc}","coach.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Hollister {cc}","hollister.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","CN":"cn"}),
    ("Abercrombie {cc}","abercrombie.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","CN":"cn"}),
    ("American Eagle {cc}","americaneagle.{domain}","moda",{"US":"com","MX":"com.mx","CA":"ca","GB":"co.uk","ES":"es","FR":"fr","DE":"de","IT":"it","NL":"nl"}),
    ("Banana Republic {cc}","bananarepublic.{domain}","moda",{"US":"com","MX":"com.mx","CA":"ca","GB":"co.uk","FR":"fr","DE":"de","IT":"it","JP":"jp"}),
    ("Old Navy {cc}","oldnavy.{domain}","moda",{"US":"com","MX":"com.mx","CA":"ca"}),
    ("Victoria Secret {cc}","victoriassecret.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it"}),
    ("Bath Body Works {cc}","bathandbodyworks.{domain}","belleza",{"US":"com","MX":"com.mx","CA":"ca","GB":"co.uk","SG":"sg","MY":"my","IN":"in","AE":"ae"}),
    ("Lush {cc}","lush.{domain}","belleza",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","IE":"ie","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","HK":"hk"}),
    ("Dyson {cc}","dyson.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","IN":"in","MY":"my","TH":"th","ID":"id"}),
    ("Nespresso {cc}","nespresso.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Lindt {cc}","lindt.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","CN":"cn"}),
    ("Coca Cola {cc}","coca-cola.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in"}),
    ("Heineken {cc}","heineken.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","CN":"cn","SG":"sg"}),
    ("Kelloggs {cc}","kelloggs.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au"}),
    ("Kraft Heinz {cc}","kraftheinz.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au"}),
    ("Pepsi {cc}","pepsi.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","CN":"cn","IN":"in"}),
    ("Armani Exchange {cc}","armaniexchange.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg"}),
    ("DKNY {cc}","dkny.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Marc Jacobs {cc}","marcjacobs.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","KR":"kr","CN":"cn"}),
    ("Kate Spade {cc}","katespade.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","KR":"kr","CN":"cn"}),
    ("Champion {cc}","champion.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Mondelez {cc}","mondelez.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au"}),
    ("Mars {cc}","mars.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au"}),
    ("Hersheys {cc}","hersheys.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","CA":"ca","GB":"co.uk","DE":"de","IN":"in","CN":"cn"}),
    ("KitchenAid {cc}","kitchenaid.{domain}","hogar",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au"}),
    ("General Mills {cc}","generalmills.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","CA":"ca","GB":"co.uk","FR":"fr","AU":"com.au"}),
    ("Diageo {cc}","diageo.{domain}","alimentos",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au","JP":"jp","CN":"cn","IN":"in","SG":"sg"}),
    ("Ray-Ban {cc}","ray-ban.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Oakley {cc}","oakley.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Sunglass Hut {cc}","sunglasshut.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg","MY":"my","TH":"th","ID":"id"}),
    ("DJI {cc}","dji.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Garmin {cc}","garmin.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg"}),
    ("Sennheiser {cc}","sennheiser.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","CN":"cn","SG":"sg"}),
    ("Bose {cc}","bose.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg"}),
    ("Yamaha {cc}","yamaha.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg","MY":"my","TH":"th","ID":"id"}),
    ("Epson {cc}","epson.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg","MY":"my","TH":"th","ID":"id","PH":"ph"}),
    ("Casio {cc}","casio.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg","MY":"my","TH":"th","ID":"id","PH":"ph"}),
    ("Seiko {cc}","seiko.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","MY":"my","TH":"th"}),
    ("Citizen {cc}","citizenwatch.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","IN":"in"}),
    ("Swarovski {cc}","swarovski.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","MY":"my","TH":"th","IN":"in","AE":"ae"}),
    ("Lego {cc}","lego.{domain}","departamentales",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg","MY":"my","TH":"th","ID":"id"}),
    ("Panasonic {cc}","panasonic.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg","MY":"my","TH":"th","ID":"id","PH":"ph","VN":"vn"}),
    ("Toshiba {cc}","toshiba.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg","MY":"my","TH":"th","ID":"id"}),
    ("Bosch {cc}","bosch.{domain}","hogar",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in","SG":"sg"}),
    ("Siemens {cc}","siemens.{domain}","hogar",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","IN":"in"}),
    ("Smeg {cc}","smeg.{domain}","hogar",{"IT":"it","GB":"co.uk","FR":"fr","DE":"de","ES":"es","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","US":"com"}),
    ("DeLonghi {cc}","delonghi.{domain}","hogar",{"IT":"it","GB":"co.uk","FR":"fr","DE":"de","ES":"es","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","US":"com","JP":"jp","KR":"kr","CN":"cn"}),
    ("Tefal {cc}","tefal.{domain}","hogar",{"FR":"fr","GB":"co.uk","DE":"de","ES":"es","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","US":"com","JP":"jp","KR":"kr","CN":"cn","SG":"sg","MY":"my","TH":"th","ID":"id","PH":"ph"}),
    ("Miele {cc}","miele.{domain}","hogar",{"DE":"de","AT":"at","CH":"ch","NL":"nl","BE":"be","FR":"fr","IT":"it","GB":"co.uk","US":"com","AU":"com.au","JP":"jp","CN":"cn"}),
    ("Rowenta {cc}","rowenta.{domain}","hogar",{"FR":"fr","GB":"co.uk","DE":"de","ES":"es","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","US":"com"}),
    ("Krups {cc}","krups.{domain}","hogar",{"DE":"de","FR":"fr","GB":"co.uk","ES":"es","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","US":"com"}),
    ("Duracell {cc}","duracell.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","CN":"cn","IN":"in"}),
    ("Energizer {cc}","energizer.{domain}","electro",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au","JP":"jp","CN":"cn","IN":"in"}),
    ("Mattel {cc}","mattel.{domain}","departamentales",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","CN":"cn"}),
    ("Hasbro {cc}","hasbro.{domain}","departamentales",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au","JP":"jp","CN":"cn"}),
    ("Tissot {cc}","tissotwatches.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","IN":"in"}),
    ("Tag Heuer {cc}","tagheuer.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Longines {cc}","longines.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Omega {cc}","omegawatches.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Montblanc {cc}","montblanc.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Cartier {cc}","cartier.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Bvlgari {cc}","bulgari.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Gaggenau {cc}","gaggenau.{domain}","hogar",{"DE":"de","AT":"at","CH":"ch","NL":"nl","BE":"be","FR":"fr","IT":"it","GB":"co.uk","US":"com","AU":"com.au"}),
    ("H&M Home {cc}","hm.{domain}","hogar",{"ES":"es","FR":"fr","IT":"it","DE":"de","GB":"com","PT":"pt","NL":"nl","AT":"at","CH":"ch","PL":"pl","CZ":"cz","RO":"ro","HU":"hu","CL":"cl","MX":"com.mx","AR":"com.ar","PE":"pe","CO":"co"}),
    ("Primark {cc}","primark.{domain}","moda",{"GB":"com","IE":"ie","ES":"es","FR":"fr","IT":"it","DE":"de","PT":"pt","NL":"nl","AT":"at","BE":"be","PL":"pl","CZ":"cz","RO":"ro","HU":"hu","SI":"si","US":"com"}),
    ("Desigual {cc}","desigual.{domain}","moda",{"ES":"com","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt","NL":"nl","AT":"at","CH":"ch","BE":"be","PL":"pl","CZ":"cz","RO":"ro","HU":"hu","TR":"tr","RU":"ru","JP":"jp","CN":"cn"}),
    ("Geox {cc}","geox.{domain}","moda",{"IT":"com","ES":"es","FR":"fr","DE":"de","GB":"co.uk","PT":"pt","NL":"nl","AT":"at","CH":"ch","BE":"be","PL":"pl","RO":"ro","TR":"tr","RU":"ru","JP":"jp","CN":"cn"}),
    ("Camper {cc}","camper.{domain}","moda",{"ES":"com","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt","NL":"nl","AT":"at","CH":"ch","BE":"be","JP":"jp","KR":"kr","CN":"cn","US":"com"}),
    ("Clarks {cc}","clarks.{domain}","moda",{"GB":"co.uk","US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","DE":"de","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","CN":"cn","IN":"in","SG":"sg"}),
    ("Dr Martens {cc}","drmartens.{domain}","moda",{"GB":"com","US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","DE":"de","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SE":"se","DK":"dk"}),
    ("Birkenstock {cc}","birkenstock.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("UGG {cc}","ugg.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","DE":"de","GB":"co.uk","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Superdry {cc}","superdry.{domain}","moda",{"GB":"com","US":"com","ES":"es","FR":"fr","IT":"it","DE":"de","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Ralph Lauren {cc}","ralphlauren.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Dolce & Gabbana {cc}","dolcegabbana.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","GB":"co.uk","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Valentino {cc}","valentino.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","GB":"co.uk","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Kenzo {cc}","kenzo.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"co.uk","DE":"de","PT":"pt","NL":"nl","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Hermes {cc}","hermes.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"co.uk","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Gucci {cc}","gucci.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"co.uk","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","MY":"my","TH":"th","AE":"ae"}),
    ("Prada {cc}","prada.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","GB":"co.uk","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","AE":"ae"}),
    ("Burberry {cc}","burberry.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","AE":"ae"}),
    ("Versace {cc}","versace.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"com","GB":"co.uk","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg","AE":"ae"}),
    ("Balenciaga {cc}","balenciaga.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Saint Laurent {cc}","ysl.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Givenchy {cc}","givenchy.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Timex {cc}","timex.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AU":"com.au","JP":"jp","CN":"cn","IN":"in"}),
    ("Hugo Boss {cc}","hugoboss.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Dior {cc}","dior.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Chanel {cc}","chanel.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Louis Vuitton {cc}","louisvuitton.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Giorgio Armani {cc}","armani.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"com","IT":"com","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Home Depot {cc}","homedepot.{domain}","hogar",{"US":"com","MX":"com.mx","CA":"ca"}),
    ("Lowes {cc}","lowes.{domain}","hogar",{"US":"com","CA":"ca"}),
    ("Obi {cc}","obi.{domain}","hogar",{"DE":"de","AT":"at","CH":"ch","IT":"it","PL":"pl","CZ":"cz","SK":"sk","HU":"hu","RO":"ro"}),
    ("Bauhaus {cc}","bauhaus.{domain}","hogar",{"DE":"de","AT":"at","CH":"ch","DK":"dk","SE":"se","FI":"fi","NO":"no","CZ":"cz","SK":"sk","HU":"hu"}),
    ("Hornbach {cc}","hornbach.{domain}","hogar",{"DE":"de","AT":"at","CH":"ch","NL":"nl","CZ":"cz","SK":"sk","RO":"ro","SE":"se"}),
    ("Fendi {cc}","fendi.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"com","GB":"com","DE":"de","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Loewe {cc}","loewe.{domain}","moda",{"ES":"com","FR":"com","IT":"it","GB":"com","DE":"de","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Bottega Veneta {cc}","bottegaveneta.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"com","GB":"com","DE":"de","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Celine {cc}","celine.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","JP":"jp","KR":"kr","CN":"cn"}),
    ("B&Q {cc}","diy.{domain}","hogar",{"GB":"com","IE":"ie"}),
    ("Castorama {cc}","castorama.{domain}","hogar",{"FR":"fr","PL":"pl"}),
    ("Brico Depot {cc}","bricodepot.{domain}","hogar",{"FR":"fr","ES":"es","PT":"pt","IT":"it","RO":"ro","PL":"pl"}),
    ("Prada {cc}","prada.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","GB":"co.uk","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Burberry {cc}","burberry.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Versace {cc}","versace.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"com","GB":"co.uk","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Saint Laurent {cc}","ysl.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Givenchy {cc}","givenchy.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","PT":"pt","NL":"nl","AT":"at","CH":"ch","AU":"com.au","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Ferrari {cc}","store.ferrari.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","GB":"com","DE":"de","IT":"com","JP":"jp","CN":"cn","SG":"sg","AE":"ae"}),
    ("Salvatore Ferragamo {cc}","ferragamo.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","GB":"com","DE":"de","IT":"com","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Marc Jacobs {cc}","marcjacobs.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","KR":"kr","CN":"cn"}),
    ("Coach {cc}","coach.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","KR":"kr","CN":"cn"}),
    ("Kate Spade {cc}","katespade.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","KR":"kr","CN":"cn"}),
    ("Tory Burch {cc}","toryburch.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","KR":"kr","CN":"cn"}),
    ("Jimmy Choo {cc}","jimmychoo.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"com","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Alexander McQueen {cc}","alexandermcqueen.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","JP":"jp","KR":"kr","CN":"cn","SG":"sg"}),
    ("Off-White {cc}","off---white.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"com","GB":"com","DE":"de","JP":"jp","KR":"kr","CN":"cn"}),
    ("Palm Angels {cc}","palmangels.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"com","IT":"it","GB":"com","DE":"de","JP":"jp","KR":"kr","CN":"cn"}),
    ("Stone Island {cc}","stoneisland.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"it","GB":"co.uk","DE":"de","NL":"nl","JP":"jp","KR":"kr","CN":"cn"}),
    ("Moncler {cc}","moncler.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","IT":"com","GB":"co.uk","DE":"de","JP":"jp","KR":"kr","CN":"cn"}),
    ("Patagonia {cc}","patagonia.{domain}","deportes",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","NL":"nl","JP":"jp","KR":"kr","CN":"cn","AU":"com.au"}),
    ("Arc'teryx {cc}","arcteryx.{domain}","deportes",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","KR":"kr","CN":"cn","AU":"com.au"}),
    ("Salomon {cc}","salomon.{domain}","deportes",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","KR":"kr","CN":"cn","AU":"com.au","SE":"se","FI":"fi","NO":"no"}),
    ("Mammut {cc}","mammut.{domain}","deportes",{"US":"com","DE":"de","AT":"at","CH":"ch","FR":"fr","IT":"it","GB":"co.uk","ES":"es","JP":"jp"}),
    ("Lululemon {cc}","lululemon.{domain}","deportes",{"US":"com","MX":"com.mx","CA":"ca","GB":"co.uk","DE":"de","FR":"fr","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Lamborghini {cc}","lamborghini.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","CN":"cn","AE":"ae"}),
    ("Bugatti {cc}","bugatti.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"com","JP":"jp","CN":"cn"}),
    ("Porsche Design {cc}","porsche-design.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","KR":"kr","CN":"cn"}),
    ("Maserati {cc}","maserati.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","CN":"cn"}),
    ("Aston Martin {cc}","astonmartin.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"com","JP":"jp","CN":"cn"}),
    ("Bentley {cc}","bentley.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"motors","JP":"jp","CN":"cn"}),
    ("Rolls-Royce {cc}","rolls-roycemotorcars.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"com","JP":"jp","CN":"cn"}),
    ("McLaren {cc}","mclaren.{domain}","moda",{"US":"com","MX":"com.mx","ES":"es","FR":"fr","GB":"com","DE":"de","IT":"com","JP":"jp","CN":"cn"}),
    ("Ducati {cc}","ducati.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","JP":"jp","CN":"cn","AE":"ae"}),
    ("Harley Davidson {cc}","harley-davidson.{domain}","moda",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au","JP":"jp","CN":"cn"}),
    ("BMW {cc}","bmw.{domain}","autopartes",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Mercedes-Benz {cc}","mercedes-benz.{domain}","autopartes",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Audi {cc}","audi.{domain}","autopartes",{"US":"com","MX":"com.mx","BR":"com.br","ES":"es","FR":"fr","GB":"co.uk","DE":"de","IT":"it","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
    ("Tesla {cc}","tesla.{domain}","autopartes",{"US":"com","MX":"com.mx","CA":"ca","GB":"co.uk","DE":"de","FR":"fr","AU":"com.au","JP":"jp","KR":"kr","CN":"cn"}),
]
if __name__ == "__main__":
    main()
