# Auto-generated — 502 retailers
STORES = {

    # ── SUPERMERCADOS ──
    "carrefour_br": {"name":"Carrefour BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "lider_cl": {"name":"Lider CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "carrefour_es": {"name":"Carrefour ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"supermercados"},
    "carrefour_fr": {"name":"Carrefour FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"supermercados"},
    "carrefour": {"name":"Carrefour AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "paodeacucar": {"name":"Pao de Acucar","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "exito": {"name":"Exito","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},
    "ta_ta_uy": {"name":"Ta-Ta","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"supermercados"},
    "jumbo_ar": {"name":"Jumbo AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "coto_ar": {"name":"Coto","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "chedraui": {"name":"Chedraui","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"supermercados"},
    "heb": {"name":"HEB","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"supermercados"},
    "olimpica": {"name":"Olimpica","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},
    "wong": {"name":"Wong","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "metro": {"name":"Metro","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "plazavea": {"name":"Plaza Vea","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "jumbo_cl": {"name":"Jumbo CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "carrefour_ar_ar": {"name":"Carrefour AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "carrefour_br_br": {"name":"Carrefour BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "carrefour_es_es": {"name":"Carrefour ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"supermercados"},
    "carrefour_fr_fr": {"name":"Carrefour FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"supermercados"},
    "carrefour_it_it": {"name":"Carrefour IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"supermercados"},
    "carrefour_be_be": {"name":"Carrefour BE","country":"BE","currency":"EUR","emoji":"🇧🇪","line":"supermercados"},
    "carrefour_ro_ro": {"name":"Carrefour RO","country":"RO","currency":"RON","emoji":"🇷🇴","line":"supermercados"},
    "carrefour_pl_pl": {"name":"Carrefour PL","country":"PL","currency":"PLN","emoji":"🌐","line":"supermercados"},
    "lider_cl_cl": {"name":"Lider CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "santa_isabel_cl_cl": {"name":"Santa Isabel CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "santa_isabel_pe_pe": {"name":"Santa Isabel PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "cencosud_ar_ar": {"name":"Cencosud AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "cencosud_cl_cl": {"name":"Cencosud CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "cencosud_pe_pe": {"name":"Cencosud PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "cencosud_co_co": {"name":"Cencosud CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},
    "cencosud_br_br": {"name":"Cencosud BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "cencosud_uy_uy": {"name":"Cencosud UY","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"supermercados"},
    "dia_ar_ar": {"name":"Dia AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "dia_br_br": {"name":"Dia BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "dia_es_es": {"name":"Dia ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"supermercados"},
    "dia_pt_pt": {"name":"Dia PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"supermercados"},
    "walmart_mx_mx": {"name":"Walmart MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"supermercados"},
    "walmart_cl_cl": {"name":"Walmart CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "walmart_ar_ar": {"name":"Walmart AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "walmart_us_us": {"name":"Walmart US","country":"US","currency":"USD","emoji":"🇺🇸","line":"supermercados"},
    "exito_co_co": {"name":"Éxito CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},
    "exito_uy_uy": {"name":"Éxito UY","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"supermercados"},
    "exito_ec_ec": {"name":"Éxito EC","country":"EC","currency":"USD","emoji":"🇪🇨","line":"supermercados"},
    "lidl_de_de": {"name":"Lidl DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"supermercados"},
    "lidl_es_es": {"name":"Lidl ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"supermercados"},
    "lidl_fr_fr": {"name":"Lidl FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"supermercados"},
    "lidl_it_it": {"name":"Lidl IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"supermercados"},
    "lidl_gb_gb": {"name":"Lidl GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"supermercados"},
    "lidl_pt_pt": {"name":"Lidl PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"supermercados"},
    "lidl_nl_nl": {"name":"Lidl NL","country":"NL","currency":"EUR","emoji":"🌐","line":"supermercados"},
    "lidl_be_be": {"name":"Lidl BE","country":"BE","currency":"EUR","emoji":"🇧🇪","line":"supermercados"},
    "lidl_pl_pl": {"name":"Lidl PL","country":"PL","currency":"PLN","emoji":"🌐","line":"supermercados"},
    "aldi_de_de": {"name":"Aldi DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"supermercados"},
    "aldi_us_us": {"name":"Aldi US","country":"US","currency":"USD","emoji":"🇺🇸","line":"supermercados"},
    "aldi_gb_gb": {"name":"Aldi GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"supermercados"},
    "aldi_fr_fr": {"name":"Aldi FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"supermercados"},
    "aldi_es_es": {"name":"Aldi ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"supermercados"},
    "aldi_it_it": {"name":"Aldi IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"supermercados"},
    "aldi_nl_nl": {"name":"Aldi NL","country":"NL","currency":"EUR","emoji":"🌐","line":"supermercados"},
    "tesco_gb_gb": {"name":"Tesco GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"supermercados"},
    "tesco_ie_ie": {"name":"Tesco IE","country":"IE","currency":"EUR","emoji":"🌐","line":"supermercados"},
    "tesco_pl_pl": {"name":"Tesco PL","country":"PL","currency":"PLN","emoji":"🌐","line":"supermercados"},
    "tesco_cz_cz": {"name":"Tesco CZ","country":"CZ","currency":"CZK","emoji":"🌐","line":"supermercados"},
    "tesco_sk_sk": {"name":"Tesco SK","country":"SK","currency":"EUR","emoji":"🌐","line":"supermercados"},
    "tesco_hu_hu": {"name":"Tesco HU","country":"HU","currency":"HUF","emoji":"🌐","line":"supermercados"},
    "carrefour_it": {"name":"Carrefour IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"supermercados"},
    "soriana_mx": {"name":"Soriana","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"supermercados"},
    "vivanda_pe": {"name":"Vivanda","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "dia_ar": {"name":"Dia AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "vea_ar": {"name":"Vea AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "gpa_extra": {"name":"Extra BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "carulla_co": {"name":"Carulla","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},
    "santaisabel_cl": {"name":"Santa Isabel CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "changomas_ar": {"name":"Changomas","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "mambo_br": {"name":"Mambo","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "surtimax_co": {"name":"Surtimax","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},

    # ── FARMACIAS ──
    "drogaraia": {"name":"Droga Raia","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"farmacias"},
    "farmatodo_co": {"name":"Farmatodo","country":"CO","currency":"COP","emoji":"🇨🇴","line":"farmacias"},
    "farmatodo_co_co": {"name":"Farmatodo CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"farmacias"},
    "farmatodo_mx_mx": {"name":"Farmatodo MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"farmacias"},
    "farmatodo_ve_ve": {"name":"Farmatodo VE","country":"VE","currency":"USD","emoji":"🌐","line":"farmacias"},
    "farmatodo_ar_ar": {"name":"Farmatodo AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"farmacias"},
    "cruz_verde_co_co": {"name":"Cruz Verde CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"farmacias"},
    "cruz_verde_cl_cl": {"name":"Cruz Verde CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"farmacias"},
    "cruz_verde_pe_pe": {"name":"Cruz Verde PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"farmacias"},
    "cruz_verde_mx_mx": {"name":"Cruz Verde MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"farmacias"},
    "farmacias_guadalajara_mx_mx": {"name":"Farmacias Guadalajara MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"farmacias"},
    "farmacias_del_ahorro_mx_mx": {"name":"Farmacias del Ahorro MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"farmacias"},
    "drogasil": {"name":"Drogasil","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"farmacias"},
    "pacheco_br": {"name":"Drogaria Pacheco","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"farmacias"},
    "inkafarma_pe": {"name":"Inkafarma","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"farmacias"},
    "boticasysalud_pe": {"name":"Boticas y Salud","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"farmacias"},

    # ── ELECTRO ──
    "magazineluiza": {"name":"Magazine Luiza","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "alkosto_co": {"name":"Alkosto","country":"CO","currency":"COP","emoji":"🇨🇴","line":"electro"},
    "samsung_br_br": {"name":"Samsung BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "samsung_mx_mx": {"name":"Samsung MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "samsung_ar_ar": {"name":"Samsung AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "samsung_cl_cl": {"name":"Samsung CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"electro"},
    "samsung_pe_pe": {"name":"Samsung PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"electro"},
    "samsung_co_co": {"name":"Samsung CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"electro"},
    "samsung_es_es": {"name":"Samsung ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "samsung_fr_fr": {"name":"Samsung FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"electro"},
    "samsung_it_it": {"name":"Samsung IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "samsung_gb_gb": {"name":"Samsung GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"electro"},
    "samsung_de_de": {"name":"Samsung DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "samsung_us_us": {"name":"Samsung US","country":"US","currency":"USD","emoji":"🇺🇸","line":"electro"},
    "samsung_pt_pt": {"name":"Samsung PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"electro"},
    "lg_br_br": {"name":"LG BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "lg_mx_mx": {"name":"LG MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "lg_ar_ar": {"name":"LG AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "lg_cl_cl": {"name":"LG CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"electro"},
    "lg_es_es": {"name":"LG ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "lg_fr_fr": {"name":"LG FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"electro"},
    "lg_it_it": {"name":"LG IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "lg_de_de": {"name":"LG DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "lg_us_us": {"name":"LG US","country":"US","currency":"USD","emoji":"🇺🇸","line":"electro"},
    "lg_pt_pt": {"name":"LG PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"electro"},
    "motorola_br_br": {"name":"Motorola BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "motorola_mx_mx": {"name":"Motorola MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "motorola_ar_ar": {"name":"Motorola AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "motorola_cl_cl": {"name":"Motorola CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"electro"},
    "motorola_es_es": {"name":"Motorola ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "motorola_it_it": {"name":"Motorola IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "motorola_gb_gb": {"name":"Motorola GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"electro"},
    "motorola_de_de": {"name":"Motorola DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "motorola_us_us": {"name":"Motorola US","country":"US","currency":"USD","emoji":"🇺🇸","line":"electro"},
    "electrolux_br_br": {"name":"Electrolux BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "electrolux_mx_mx": {"name":"Electrolux MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "electrolux_ar_ar": {"name":"Electrolux AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "electrolux_cl_cl": {"name":"Electrolux CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"electro"},
    "electrolux_es_es": {"name":"Electrolux ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "electrolux_it_it": {"name":"Electrolux IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "electrolux_fr_fr": {"name":"Electrolux FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"electro"},
    "electrolux_de_de": {"name":"Electrolux DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "electrolux_se_se": {"name":"Electrolux SE","country":"SE","currency":"SEK","emoji":"🌐","line":"electro"},
    "electrolux_pt_pt": {"name":"Electrolux PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"electro"},
    "electrolux_nl_nl": {"name":"Electrolux NL","country":"NL","currency":"EUR","emoji":"🌐","line":"electro"},
    "whirlpool_br_br": {"name":"Whirlpool BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "whirlpool_mx_mx": {"name":"Whirlpool MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "whirlpool_ar_ar": {"name":"Whirlpool AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "whirlpool_es_es": {"name":"Whirlpool ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "whirlpool_it_it": {"name":"Whirlpool IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "whirlpool_fr_fr": {"name":"Whirlpool FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"electro"},
    "whirlpool_de_de": {"name":"Whirlpool DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "whirlpool_gb_gb": {"name":"Whirlpool GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"electro"},
    "whirlpool_us_us": {"name":"Whirlpool US","country":"US","currency":"USD","emoji":"🇺🇸","line":"electro"},
    "whirlpool_pt_pt": {"name":"Whirlpool PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"electro"},
    "garbarino_ar_ar": {"name":"Garbarino AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "mediamarkt_es_es": {"name":"MediaMarkt ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "mediamarkt_de_de": {"name":"MediaMarkt DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "mediamarkt_it_it": {"name":"MediaMarkt IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "mediamarkt_nl_nl": {"name":"MediaMarkt NL","country":"NL","currency":"EUR","emoji":"🌐","line":"electro"},
    "mediamarkt_pl_pl": {"name":"MediaMarkt PL","country":"PL","currency":"PLN","emoji":"🌐","line":"electro"},
    "mediamarkt_pt_pt": {"name":"MediaMarkt PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"electro"},
    "mediamarkt_at_at": {"name":"MediaMarkt AT","country":"AT","currency":"EUR","emoji":"🌐","line":"electro"},
    "casas_bahia_br_br": {"name":"Casas Bahia BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "ponto_frio_br_br": {"name":"Ponto Frio BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "magazine_luiza_br_br": {"name":"Magazine Luiza BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "samsung_mx": {"name":"Samsung MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "fravega_ar": {"name":"Fravega","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "samsung_br": {"name":"Samsung BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "lg_br": {"name":"LG BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "casasbahia_br": {"name":"Casas Bahia","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "alkomprar_co": {"name":"Alkomprar","country":"CO","currency":"COP","emoji":"🇨🇴","line":"electro"},
    "musimundo_ar": {"name":"Musimundo","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "pontofrio_br": {"name":"Ponto Frio","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "motorola_br": {"name":"Motorola BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "electrolux_br": {"name":"Electrolux BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "whirlpool_br": {"name":"Whirlpool BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},

    # ── DEPORTES ──
    "centauro": {"name":"Centauro BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "decathlon_fr": {"name":"Decathlon FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"deportes"},
    "decathlon_es": {"name":"Decathlon ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"deportes"},
    "decathlon_it": {"name":"Decathlon IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"deportes"},
    "decathlon_pt": {"name":"Decathlon PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"deportes"},
    "decathlon_cl": {"name":"Decathlon CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"deportes"},
    "decathlon_fr_fr": {"name":"Decathlon FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"deportes"},
    "decathlon_es_es": {"name":"Decathlon ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"deportes"},
    "decathlon_it_it": {"name":"Decathlon IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"deportes"},
    "decathlon_de_de": {"name":"Decathlon DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"deportes"},
    "decathlon_gb_gb": {"name":"Decathlon GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"deportes"},
    "decathlon_pt_pt": {"name":"Decathlon PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"deportes"},
    "decathlon_nl_nl": {"name":"Decathlon NL","country":"NL","currency":"EUR","emoji":"🌐","line":"deportes"},
    "decathlon_be_be": {"name":"Decathlon BE","country":"BE","currency":"EUR","emoji":"🇧🇪","line":"deportes"},
    "decathlon_pl_pl": {"name":"Decathlon PL","country":"PL","currency":"PLN","emoji":"🌐","line":"deportes"},
    "decathlon_br_br": {"name":"Decathlon BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "decathlon_cl_cl": {"name":"Decathlon CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"deportes"},
    "decathlon_pe_pe": {"name":"Decathlon PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"deportes"},
    "decathlon_co_co": {"name":"Decathlon CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"deportes"},
    "decathlon_ar_ar": {"name":"Decathlon AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"deportes"},
    "decathlon_mx_mx": {"name":"Decathlon MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "decathlon_se_se": {"name":"Decathlon SE","country":"SE","currency":"SEK","emoji":"🌐","line":"deportes"},
    "nike_br_br": {"name":"Nike BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "nike_mx_mx": {"name":"Nike MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "nike_ar_ar": {"name":"Nike AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"deportes"},
    "nike_cl_cl": {"name":"Nike CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"deportes"},
    "nike_pe_pe": {"name":"Nike PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"deportes"},
    "nike_co_co": {"name":"Nike CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"deportes"},
    "nike_es_es": {"name":"Nike ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"deportes"},
    "nike_fr_fr": {"name":"Nike FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"deportes"},
    "nike_it_it": {"name":"Nike IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"deportes"},
    "nike_de_de": {"name":"Nike DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"deportes"},
    "nike_gb_gb": {"name":"Nike GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"deportes"},
    "nike_pt_pt": {"name":"Nike PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"deportes"},
    "nike_nl_nl": {"name":"Nike NL","country":"NL","currency":"EUR","emoji":"🌐","line":"deportes"},
    "nike_se_se": {"name":"Nike SE","country":"SE","currency":"SEK","emoji":"🌐","line":"deportes"},
    "nike_pl_pl": {"name":"Nike PL","country":"PL","currency":"PLN","emoji":"🌐","line":"deportes"},
    "adidas_br_br": {"name":"Adidas BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "adidas_mx_mx": {"name":"Adidas MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "adidas_ar_ar": {"name":"Adidas AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"deportes"},
    "adidas_cl_cl": {"name":"Adidas CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"deportes"},
    "adidas_pe_pe": {"name":"Adidas PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"deportes"},
    "adidas_co_co": {"name":"Adidas CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"deportes"},
    "adidas_es_es": {"name":"Adidas ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"deportes"},
    "adidas_fr_fr": {"name":"Adidas FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"deportes"},
    "adidas_it_it": {"name":"Adidas IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"deportes"},
    "adidas_de_de": {"name":"Adidas DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"deportes"},
    "adidas_gb_gb": {"name":"Adidas GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"deportes"},
    "adidas_pt_pt": {"name":"Adidas PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"deportes"},
    "adidas_nl_nl": {"name":"Adidas NL","country":"NL","currency":"EUR","emoji":"🌐","line":"deportes"},
    "adidas_pl_pl": {"name":"Adidas PL","country":"PL","currency":"PLN","emoji":"🌐","line":"deportes"},
    "adidas_se_se": {"name":"Adidas SE","country":"SE","currency":"SEK","emoji":"🌐","line":"deportes"},
    "puma_br_br": {"name":"Puma BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "puma_mx_mx": {"name":"Puma MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "puma_ar_ar": {"name":"Puma AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"deportes"},
    "puma_es_es": {"name":"Puma ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"deportes"},
    "puma_fr_fr": {"name":"Puma FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"deportes"},
    "puma_it_it": {"name":"Puma IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"deportes"},
    "puma_de_de": {"name":"Puma DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"deportes"},
    "puma_gb_gb": {"name":"Puma GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"deportes"},
    "puma_pt_pt": {"name":"Puma PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"deportes"},
    "puma_nl_nl": {"name":"Puma NL","country":"NL","currency":"EUR","emoji":"🌐","line":"deportes"},
    "centauro_br_br": {"name":"Centauro BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "netshoes_br_br": {"name":"Netshoes BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "nike_br": {"name":"Nike BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "adidas_br": {"name":"Adidas BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "decathlon_br": {"name":"Decathlon BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "decathlon_uk": {"name":"Decathlon UK","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"deportes"},
    "marti_mx": {"name":"Marti","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "decathlon_co": {"name":"Decathlon CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"deportes"},
    "decathlon_ar": {"name":"Decathlon AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"deportes"},
    "decathlon_mx": {"name":"Decathlon MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "decathlon_pe": {"name":"Decathlon PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"deportes"},

    # ── HOGAR ──
    "sodimac_co_co": {"name":"Sodimac CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"hogar"},
    "sodimac_cl_cl": {"name":"Sodimac CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"hogar"},
    "sodimac_pe_pe": {"name":"Sodimac PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"hogar"},
    "sodimac_ar_ar": {"name":"Sodimac AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"hogar"},
    "sodimac_br_br": {"name":"Sodimac BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"hogar"},
    "sodimac_mx_mx": {"name":"Sodimac MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"hogar"},
    "sodimac_uy_uy": {"name":"Sodimac UY","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"hogar"},
    "easy_ar_ar": {"name":"Easy AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"hogar"},
    "easy_cl_cl": {"name":"Easy CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"hogar"},
    "easy_co_co": {"name":"Easy CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"hogar"},
    "easy_pe_pe": {"name":"Easy PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"hogar"},
    "leroy_merlin_br_br": {"name":"Leroy Merlin BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"hogar"},
    "leroy_merlin_es_es": {"name":"Leroy Merlin ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"hogar"},
    "leroy_merlin_fr_fr": {"name":"Leroy Merlin FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"hogar"},
    "leroy_merlin_it_it": {"name":"Leroy Merlin IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"hogar"},
    "leroy_merlin_pt_pt": {"name":"Leroy Merlin PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"hogar"},
    "leroy_merlin_pl_pl": {"name":"Leroy Merlin PL","country":"PL","currency":"PLN","emoji":"🌐","line":"hogar"},
    "leroy_merlin_ro_ro": {"name":"Leroy Merlin RO","country":"RO","currency":"RON","emoji":"🇷🇴","line":"hogar"},
    "rosen_cl_cl": {"name":"Rosen CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"hogar"},
    "rosen_pe_pe": {"name":"Rosen PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"hogar"},
    "rosen_co_co": {"name":"Rosen CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"hogar"},
    "rosen_mx_mx": {"name":"Rosen MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"hogar"},
    "rosen_ar_ar": {"name":"Rosen AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"hogar"},
    "rosen_ec_ec": {"name":"Rosen EC","country":"EC","currency":"USD","emoji":"🇪🇨","line":"hogar"},
    "ikea_es_es": {"name":"IKEA ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"hogar"},
    "ikea_fr_fr": {"name":"IKEA FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"hogar"},
    "ikea_it_it": {"name":"IKEA IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"hogar"},
    "ikea_de_de": {"name":"IKEA DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"hogar"},
    "ikea_gb_gb": {"name":"IKEA GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"hogar"},
    "ikea_pt_pt": {"name":"IKEA PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"hogar"},
    "ikea_nl_nl": {"name":"IKEA NL","country":"NL","currency":"EUR","emoji":"🌐","line":"hogar"},
    "ikea_be_be": {"name":"IKEA BE","country":"BE","currency":"EUR","emoji":"🇧🇪","line":"hogar"},
    "ikea_pl_pl": {"name":"IKEA PL","country":"PL","currency":"PLN","emoji":"🌐","line":"hogar"},
    "mobly_br_br": {"name":"Mobly BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"hogar"},
    "homecenter": {"name":"Homecenter CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"hogar"},
    "sodimac_cl": {"name":"Sodimac CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"hogar"},
    "easy_ar": {"name":"Easy AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"hogar"},
    "leroymerlin_br": {"name":"Leroy Merlin BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"hogar"},
    "sodimac_co": {"name":"Sodimac CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"hogar"},
    "promart_pe": {"name":"Promart","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"hogar"},
    "rosen_cl": {"name":"Rosen CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"hogar"},

    # ── DEPARTAMENTALES ──
    "ripley_cl_cl": {"name":"Ripley CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"departamentales"},
    "ripley_pe_pe": {"name":"Ripley PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"departamentales"},
    "ripley_co_co": {"name":"Ripley CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"departamentales"},
    "ripley_mx_mx": {"name":"Ripley MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "ripley_ar_ar": {"name":"Ripley AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"departamentales"},
    "falabella_cl_cl": {"name":"Falabella CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"departamentales"},
    "falabella_pe_pe": {"name":"Falabella PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"departamentales"},
    "falabella_co_co": {"name":"Falabella CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"departamentales"},
    "falabella_ar_ar": {"name":"Falabella AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"departamentales"},
    "falabella_br_br": {"name":"Falabella BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"departamentales"},
    "falabella_mx_mx": {"name":"Falabella MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "falabella_uy_uy": {"name":"Falabella UY","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"departamentales"},
    "coppel_mx_mx": {"name":"Coppel MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "coppel_ar_ar": {"name":"Coppel AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"departamentales"},
    "liverpool_mx": {"name":"Liverpool","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "palacio_mx": {"name":"Palacio Hierro","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "paris_cl": {"name":"Paris CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"departamentales"},
    "sears_mx": {"name":"Sears MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "oechsle_pe": {"name":"Oechsle","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"departamentales"},
    "sanborns_mx": {"name":"Sanborns","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "lapolar_cl": {"name":"La Polar CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"departamentales"},

    # ── MODA ──
    "ca_br_br": {"name":"C&A BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "ca_mx_mx": {"name":"C&A MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "ca_ar_ar": {"name":"C&A AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "ca_cl_cl": {"name":"C&A CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"moda"},
    "ca_pe_pe": {"name":"C&A PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "ca_co_co": {"name":"C&A CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "ca_es_es": {"name":"C&A ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"moda"},
    "ca_fr_fr": {"name":"C&A FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"moda"},
    "ca_de_de": {"name":"C&A DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"moda"},
    "ca_it_it": {"name":"C&A IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"moda"},
    "ca_pt_pt": {"name":"C&A PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"moda"},
    "ca_nl_nl": {"name":"C&A NL","country":"NL","currency":"EUR","emoji":"🌐","line":"moda"},
    "hering_br_br": {"name":"Hering BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "hering_mx_mx": {"name":"Hering MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "hering_ar_ar": {"name":"Hering AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "hering_cl_cl": {"name":"Hering CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"moda"},
    "hering_pe_pe": {"name":"Hering PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "hering_co_co": {"name":"Hering CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "zara_es_es": {"name":"Zara ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"moda"},
    "zara_fr_fr": {"name":"Zara FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"moda"},
    "zara_it_it": {"name":"Zara IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"moda"},
    "zara_de_de": {"name":"Zara DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"moda"},
    "zara_gb_gb": {"name":"Zara GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"moda"},
    "zara_pt_pt": {"name":"Zara PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"moda"},
    "zara_nl_nl": {"name":"Zara NL","country":"NL","currency":"EUR","emoji":"🌐","line":"moda"},
    "zara_cl_cl": {"name":"Zara CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"moda"},
    "zara_mx_mx": {"name":"Zara MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "zara_ar_ar": {"name":"Zara AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "zara_co_co": {"name":"Zara CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "zara_pe_pe": {"name":"Zara PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "zara_br_br": {"name":"Zara BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "mango_es_es": {"name":"Mango ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"moda"},
    "mango_fr_fr": {"name":"Mango FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"moda"},
    "mango_it_it": {"name":"Mango IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"moda"},
    "mango_de_de": {"name":"Mango DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"moda"},
    "mango_gb_gb": {"name":"Mango GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"moda"},
    "mango_pt_pt": {"name":"Mango PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"moda"},
    "mango_nl_nl": {"name":"Mango NL","country":"NL","currency":"EUR","emoji":"🌐","line":"moda"},
    "leonisa_co_co": {"name":"Leonisa CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "leonisa_pe_pe": {"name":"Leonisa PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "leonisa_mx_mx": {"name":"Leonisa MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "leonisa_es_es": {"name":"Leonisa ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"moda"},
    "leonisa_us_us": {"name":"Leonisa US","country":"US","currency":"USD","emoji":"🇺🇸","line":"moda"},
    "totto_co_co": {"name":"Totto CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "totto_pe_pe": {"name":"Totto PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "totto_ec_ec": {"name":"Totto EC","country":"EC","currency":"USD","emoji":"🇪🇨","line":"moda"},
    "totto_mx_mx": {"name":"Totto MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "totto_cr_cr": {"name":"Totto CR","country":"CR","currency":"CRC","emoji":"🇨🇷","line":"moda"},
    "totto_gt_gt": {"name":"Totto GT","country":"GT","currency":"GTQ","emoji":"🌐","line":"moda"},
    "totto_pa_pa": {"name":"Totto PA","country":"PA","currency":"USD","emoji":"🇵🇦","line":"moda"},
    "totto_bo_bo": {"name":"Totto BO","country":"BO","currency":"BOB","emoji":"🌐","line":"moda"},
    "hm_es_es": {"name":"H&M ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"moda"},
    "hm_fr_fr": {"name":"H&M FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"moda"},
    "hm_it_it": {"name":"H&M IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"moda"},
    "hm_de_de": {"name":"H&M DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"moda"},
    "hm_gb_gb": {"name":"H&M GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"moda"},
    "hm_pt_pt": {"name":"H&M PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"moda"},
    "hm_nl_nl": {"name":"H&M NL","country":"NL","currency":"EUR","emoji":"🌐","line":"moda"},
    "hm_cl_cl": {"name":"H&M CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"moda"},
    "hm_mx_mx": {"name":"H&M MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "hm_ar_ar": {"name":"H&M AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "hm_pe_pe": {"name":"H&M PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "hm_co_co": {"name":"H&M CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "hm_br_br": {"name":"H&M BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "marisa_br_br": {"name":"Marisa BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "marisa_ar_ar": {"name":"Marisa AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "riachuelo_br_br": {"name":"Riachuelo BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "dafiti_br_br": {"name":"Dafiti BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "dafiti_mx_mx": {"name":"Dafiti MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "dafiti_ar_ar": {"name":"Dafiti AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "dafiti_cl_cl": {"name":"Dafiti CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"moda"},
    "dafiti_co_co": {"name":"Dafiti CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "dafiti_pe_pe": {"name":"Dafiti PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "renner": {"name":"Lojas Renner","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "ca_mx": {"name":"C&A MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "ca_br": {"name":"C&A BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "marisa_br": {"name":"Marisa","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "riachuelo_br": {"name":"Riachuelo","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "arturocalle_co": {"name":"Arturo Calle","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "leonisa_co": {"name":"Leonisa","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "totto_co": {"name":"Totto","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},

    # ── BELLEZA ──
    "o_boticario_br_br": {"name":"O Boticário BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "o_boticario_pt_pt": {"name":"O Boticário PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"belleza"},
    "o_boticario_ar_ar": {"name":"O Boticário AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"belleza"},
    "o_boticario_cl_cl": {"name":"O Boticário CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"belleza"},
    "o_boticario_pe_pe": {"name":"O Boticário PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"belleza"},
    "o_boticario_co_co": {"name":"O Boticário CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"belleza"},
    "o_boticario_mx_mx": {"name":"O Boticário MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "o_boticario_bo_bo": {"name":"O Boticário BO","country":"BO","currency":"BOB","emoji":"🌐","line":"belleza"},
    "o_boticario_py_py": {"name":"O Boticário PY","country":"PY","currency":"PYG","emoji":"🌐","line":"belleza"},
    "o_boticario_uy_uy": {"name":"O Boticário UY","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"belleza"},
    "o_boticario_es_es": {"name":"O Boticário ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"belleza"},
    "o_boticario_fr_fr": {"name":"O Boticário FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"belleza"},
    "o_boticario_it_it": {"name":"O Boticário IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"belleza"},
    "o_boticario_de_de": {"name":"O Boticário DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"belleza"},
    "o_boticario_gb_gb": {"name":"O Boticário GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"belleza"},
    "o_boticario_us_us": {"name":"O Boticário US","country":"US","currency":"USD","emoji":"🇺🇸","line":"belleza"},
    "natura_br_br": {"name":"Natura BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "natura_mx_mx": {"name":"Natura MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "natura_ar_ar": {"name":"Natura AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"belleza"},
    "natura_cl_cl": {"name":"Natura CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"belleza"},
    "natura_pe_pe": {"name":"Natura PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"belleza"},
    "natura_co_co": {"name":"Natura CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"belleza"},
    "natura_bo_bo": {"name":"Natura BO","country":"BO","currency":"BOB","emoji":"🌐","line":"belleza"},
    "natura_fr_fr": {"name":"Natura FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"belleza"},
    "avon_br_br": {"name":"Avon BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "avon_mx_mx": {"name":"Avon MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "avon_ar_ar": {"name":"Avon AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"belleza"},
    "avon_cl_cl": {"name":"Avon CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"belleza"},
    "avon_es_es": {"name":"Avon ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"belleza"},
    "avon_fr_fr": {"name":"Avon FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"belleza"},
    "avon_it_it": {"name":"Avon IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"belleza"},
    "avon_de_de": {"name":"Avon DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"belleza"},
    "avon_gb_gb": {"name":"Avon GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"belleza"},
    "avon_pt_pt": {"name":"Avon PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"belleza"},
    "avon_pl_pl": {"name":"Avon PL","country":"PL","currency":"PLN","emoji":"🌐","line":"belleza"},
    "sephora_br_br": {"name":"Sephora BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "sephora_mx_mx": {"name":"Sephora MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "sephora_es_es": {"name":"Sephora ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"belleza"},
    "sephora_fr_fr": {"name":"Sephora FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"belleza"},
    "sephora_it_it": {"name":"Sephora IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"belleza"},
    "sephora_de_de": {"name":"Sephora DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"belleza"},
    "sephora_gb_gb": {"name":"Sephora GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"belleza"},
    "sephora_pt_pt": {"name":"Sephora PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"belleza"},
    "mac_br_br": {"name":"MAC BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "mac_mx_mx": {"name":"MAC MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "mac_ar_ar": {"name":"MAC AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"belleza"},
    "mac_es_es": {"name":"MAC ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"belleza"},
    "mac_fr_fr": {"name":"MAC FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"belleza"},
    "mac_it_it": {"name":"MAC IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"belleza"},
    "mac_de_de": {"name":"MAC DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"belleza"},
    "mac_gb_gb": {"name":"MAC GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"belleza"},
    "mac_pt_pt": {"name":"MAC PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"belleza"},
    "oboticario_br": {"name":"O Boticario","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "natura_br": {"name":"Natura BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "natura_mx": {"name":"Natura MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "natura_co": {"name":"Natura CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"belleza"},
    "avon_br": {"name":"Avon BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "natura_cl": {"name":"Natura CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"belleza"},

    # ── ALIMENTOS ──
    "nestle_br_br": {"name":"Nestlé BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "nestle_mx_mx": {"name":"Nestlé MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"alimentos"},
    "nestle_ar_ar": {"name":"Nestlé AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"alimentos"},
    "nestle_es_es": {"name":"Nestlé ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"alimentos"},
    "nestle_fr_fr": {"name":"Nestlé FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"alimentos"},
    "nestle_it_it": {"name":"Nestlé IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"alimentos"},
    "nestle_de_de": {"name":"Nestlé DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"alimentos"},
    "nestle_pt_pt": {"name":"Nestlé PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"alimentos"},
    "nestle_cl_cl": {"name":"Nestlé CL","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"alimentos"},
    "nestle_co_co": {"name":"Nestlé CO","country":"CO","currency":"COP","emoji":"🇨🇴","line":"alimentos"},
    "nestle_pe_pe": {"name":"Nestlé PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"alimentos"},
    "nestle_gb_gb": {"name":"Nestlé GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"alimentos"},
    "unilever_br_br": {"name":"Unilever BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "unilever_mx_mx": {"name":"Unilever MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"alimentos"},
    "unilever_ar_ar": {"name":"Unilever AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"alimentos"},
    "unilever_es_es": {"name":"Unilever ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"alimentos"},
    "unilever_fr_fr": {"name":"Unilever FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"alimentos"},
    "unilever_it_it": {"name":"Unilever IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"alimentos"},
    "unilever_de_de": {"name":"Unilever DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"alimentos"},
    "unilever_gb_gb": {"name":"Unilever GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"alimentos"},
    "unilever_pt_pt": {"name":"Unilever PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"alimentos"},
    "unilever_nl_nl": {"name":"Unilever NL","country":"NL","currency":"EUR","emoji":"🌐","line":"alimentos"},
    "danone_br_br": {"name":"Danone BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "danone_mx_mx": {"name":"Danone MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"alimentos"},
    "danone_ar_ar": {"name":"Danone AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"alimentos"},
    "danone_es_es": {"name":"Danone ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"alimentos"},
    "danone_fr_fr": {"name":"Danone FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"alimentos"},
    "danone_it_it": {"name":"Danone IT","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"alimentos"},
    "danone_de_de": {"name":"Danone DE","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"alimentos"},
    "danone_pt_pt": {"name":"Danone PT","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"alimentos"},
    "swift_br_br": {"name":"Swift BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "swift_ar_ar": {"name":"Swift AR","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"alimentos"},
    "swift_uy_uy": {"name":"Swift UY","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"alimentos"},
    "nestle_br": {"name":"Nestle BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "unilever_br": {"name":"Unilever BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "swift_br": {"name":"Swift BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},

    # ── LIBRERIA ──
    "office_depot_mx_mx": {"name":"Office Depot MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"libreria"},
    "office_depot_es_es": {"name":"Office Depot ES","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"libreria"},
    "office_depot_fr_fr": {"name":"Office Depot FR","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"libreria"},
    "office_depot_gb_gb": {"name":"Office Depot GB","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"libreria"},
    "office_depot_us_us": {"name":"Office Depot US","country":"US","currency":"USD","emoji":"🇺🇸","line":"libreria"},
    "office_depot_pe_pe": {"name":"Office Depot PE","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"libreria"},
    "saraiva_br_br": {"name":"Saraiva BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"libreria"},
    "livraria_cultura_br_br": {"name":"Livraria Cultura BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"libreria"},
    "saraiva_br": {"name":"Saraiva","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"libreria"},
    "officedepot_mx": {"name":"Office Depot MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"libreria"},
    "tailoy_pe": {"name":"Tai Loy","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"libreria"},

    # ── AUTOPARTES ──
    "autozone_mx_mx": {"name":"AutoZone MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"autopartes"},
    "autozone_us_us": {"name":"AutoZone US","country":"US","currency":"USD","emoji":"🇺🇸","line":"autopartes"},
    "autozone_br_br": {"name":"AutoZone BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"autopartes"},
    "autozone_mx": {"name":"AutoZone MX","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"autopartes"},

    # ── MASCOTAS ──
    "petlove_br_br": {"name":"Petlove BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
    "petz_br_br": {"name":"Petz BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
    "cobasi_br_br": {"name":"Cobasi BR","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
    "petlove_br": {"name":"Petlove","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
    "petz_br": {"name":"Petz","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
    "cobasi_br": {"name":"Cobasi","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
}

