# Auto-generated — verified VTEX stores with working public APIs
# 27 retailers | 8 countries | 4 lines
STORES = {
    "carrefour": {"name":"Carrefour AR","base":"https://www.carrefour.com.ar","country":"AR","currency":"ARS","emoji":"","line":"supermercados"},
    "exito_co": {"name":"Exito CO","base":"https://www.exito.com","country":"CO","currency":"COP","emoji":"","line":"supermercados"},
    "vea_ar": {"name":"Vea AR","base":"https://www.vea.com.ar","country":"AR","currency":"ARS","emoji":"","line":"supermercados"},
    "jumbo_ar": {"name":"Jumbo AR","base":"https://www.jumbo.com.ar","country":"AR","currency":"ARS","emoji":"","line":"supermercados"},
    "easy_ar": {"name":"Easy AR","base":"https://www.easy.com.ar","country":"AR","currency":"ARS","emoji":"","line":"hogar"},
    "electrolux_ar": {"name":"Electrolux AR","base":"https://www.electrolux.com.ar","country":"AR","currency":"ARS","emoji":"","line":"electro"},
    "motorola_ar": {"name":"Motorola AR","base":"https://www.motorola.com.ar","country":"AR","currency":"ARS","emoji":"","line":"electro"},
    "whirlpool_ar": {"name":"Whirlpool AR","base":"https://www.whirlpool.com.ar","country":"AR","currency":"ARS","emoji":"","line":"electro"},
    "carrefour_br": {"name":"Carrefour BR","base":"https://www.carrefour.com.br","country":"BR","currency":"BRL","emoji":"","line":"supermercados"},
    "sams_club_br": {"name":"Sam's Club BR","base":"https://www.samsclub.com.br","country":"BR","currency":"BRL","emoji":"","line":"supermercados"},
    "mambo_br": {"name":"Mambo BR","base":"https://www.mambo.com.br","country":"BR","currency":"BRL","emoji":"","line":"supermercados"},
    "pacheco_br": {"name":"Drogaria Pacheco","base":"https://www.drogariaspacheco.com.br","country":"BR","currency":"BRL","emoji":"","line":"farmacias"},
    "motorola_br": {"name":"Motorola BR","base":"https://www.motorola.com.br","country":"BR","currency":"BRL","emoji":"","line":"electro"},
    "chedraui": {"name":"Chedraui","base":"https://www.chedraui.com.mx","country":"MX","currency":"MXN","emoji":"","line":"supermercados"},
    "heb_mx": {"name":"HEB","base":"https://www.heb.com.mx","country":"MX","currency":"MXN","emoji":"","line":"supermercados"},
    "farmatodo_mx": {"name":"Farmatodo MX","base":"https://www.farmatodo.com.mx","country":"MX","currency":"MXN","emoji":"","line":"farmacias"},
    "motorola_mx": {"name":"Motorola MX","base":"https://www.motorola.com.mx","country":"MX","currency":"MXN","emoji":"","line":"electro"},
    "exito": {"name":"Éxito","base":"https://www.exito.com","country":"CO","currency":"COP","emoji":"","line":"supermercados"},
    "carulla": {"name":"Carulla","base":"https://www.carulla.com","country":"CO","currency":"COP","emoji":"","line":"supermercados"},
    "olimpica": {"name":"Olímpica","base":"https://www.olimpica.com","country":"CO","currency":"COP","emoji":"","line":"supermercados"},
    "wong": {"name":"Wong","base":"https://www.wong.pe","country":"PE","currency":"PEN","emoji":"","line":"supermercados"},
    "metro": {"name":"Metro","base":"https://www.metro.pe","country":"PE","currency":"PEN","emoji":"","line":"supermercados"},
    "plazavea": {"name":"Plaza Vea","base":"https://www.plazavea.com.pe","country":"PE","currency":"PEN","emoji":"","line":"supermercados"},
    "electrolux_cl": {"name":"Electrolux CL","base":"https://www.electrolux.cl","country":"CL","currency":"CLP","emoji":"","line":"electro"},
    "motorola_cl": {"name":"Motorola CL","base":"https://www.motorola.cl","country":"CL","currency":"CLP","emoji":"","line":"electro"},
    "whirlpool_it": {"name":"Whirlpool IT","base":"https://www.whirlpool.it","country":"IT","currency":"EUR","emoji":"","line":"electro"},
    "whirlpool_fr": {"name":"Whirlpool FR","base":"https://www.whirlpool.fr","country":"FR","currency":"EUR","emoji":"","line":"electro"},
}
