# Auto-generated — 502 retailers
STORES = {

    # ── SUPERMERCADOS ──
    "carrefour_br": {"name":"Carrefour BR","base":"https://www.carrefour.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "lider_cl": {"name":"Lider CL","base":"https://www.lider.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "carrefour_es": {"name":"Carrefour ES","base":"https://www.carrefour.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"supermercados"},
    "carrefour_fr": {"name":"Carrefour FR","base":"https://www.carrefour.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"supermercados"},
    "carrefour": {"name":"Carrefour AR","base":"https://www.carrefour.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "paodeacucar": {"name":"Pao de Acucar","base":"https://www.paodeacucar.com","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "exito": {"name":"Exito","base":"https://www.exito.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},
    "ta_ta_uy": {"name":"Ta-Ta","base":"https://www.tata.com.uy","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"supermercados"},
    "jumbo_ar": {"name":"Jumbo AR","base":"https://www.jumbo.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "coto_ar": {"name":"Coto","base":"https://www.coto.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "chedraui": {"name":"Chedraui","base":"https://www.chedraui.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"supermercados"},
    "heb": {"name":"HEB","base":"https://www.heb.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"supermercados"},
    "olimpica": {"name":"Olimpica","base":"https://www.olimpica.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},
    "wong": {"name":"Wong","base":"https://www.wong.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "metro": {"name":"Metro","base":"https://www.metro.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "plazavea": {"name":"Plaza Vea","base":"https://www.plazavea.com.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "jumbo_cl": {"name":"Jumbo CL","base":"https://www.jumbo.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "carrefour_ar_ar": {"name":"Carrefour AR","base":"https://www.carrefour.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "carrefour_br_br": {"name":"Carrefour BR","base":"https://www.carrefour.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "carrefour_es_es": {"name":"Carrefour ES","base":"https://www.carrefour.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"supermercados"},
    "carrefour_fr_fr": {"name":"Carrefour FR","base":"https://www.carrefour.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"supermercados"},
    "carrefour_it_it": {"name":"Carrefour IT","base":"https://www.carrefour.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"supermercados"},
    "carrefour_be_be": {"name":"Carrefour BE","base":"https://www.carrefour.be","country":"BE","currency":"EUR","emoji":"🇧🇪","line":"supermercados"},
    "carrefour_ro_ro": {"name":"Carrefour RO","base":"https://www.carrefour.ro","country":"RO","currency":"RON","emoji":"🇷🇴","line":"supermercados"},
    "carrefour_pl_pl": {"name":"Carrefour PL","base":"https://www.carrefour.pl","country":"PL","currency":"PLN","emoji":"🌐","line":"supermercados"},
    "lider_cl_cl": {"name":"Lider CL","base":"https://www.lider.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "santa_isabel_cl_cl": {"name":"Santa Isabel CL","base":"https://www.santaisabel.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "santa_isabel_pe_pe": {"name":"Santa Isabel PE","base":"https://www.santaisabel.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "cencosud_ar_ar": {"name":"Cencosud AR","base":"https://www.cencosud.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "cencosud_cl_cl": {"name":"Cencosud CL","base":"https://www.cencosud.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "cencosud_pe_pe": {"name":"Cencosud PE","base":"https://www.cencosud.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "cencosud_co_co": {"name":"Cencosud CO","base":"https://www.cencosud.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},
    "cencosud_br_br": {"name":"Cencosud BR","base":"https://www.cencosud.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "cencosud_uy_uy": {"name":"Cencosud UY","base":"https://www.cencosud.uy","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"supermercados"},
    "dia_ar_ar": {"name":"Dia AR","base":"https://www.dia.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "dia_br_br": {"name":"Dia BR","base":"https://www.dia.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "dia_es_es": {"name":"Dia ES","base":"https://www.dia.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"supermercados"},
    "dia_pt_pt": {"name":"Dia PT","base":"https://www.dia.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"supermercados"},
    "walmart_mx_mx": {"name":"Walmart MX","base":"https://www.walmart.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"supermercados"},
    "walmart_cl_cl": {"name":"Walmart CL","base":"https://www.walmart.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "walmart_ar_ar": {"name":"Walmart AR","base":"https://www.walmart.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "walmart_us_us": {"name":"Walmart US","base":"https://www.walmart.com","country":"US","currency":"USD","emoji":"🇺🇸","line":"supermercados"},
    "exito_co_co": {"name":"Éxito CO","base":"https://www.exito.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},
    "exito_uy_uy": {"name":"Éxito UY","base":"https://www.exito.uy","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"supermercados"},
    "exito_ec_ec": {"name":"Éxito EC","base":"https://www.exito.ec","country":"EC","currency":"USD","emoji":"🇪🇨","line":"supermercados"},
    "lidl_de_de": {"name":"Lidl DE","base":"https://www.lidl.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"supermercados"},
    "lidl_es_es": {"name":"Lidl ES","base":"https://www.lidl.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"supermercados"},
    "lidl_fr_fr": {"name":"Lidl FR","base":"https://www.lidl.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"supermercados"},
    "lidl_it_it": {"name":"Lidl IT","base":"https://www.lidl.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"supermercados"},
    "lidl_gb_gb": {"name":"Lidl GB","base":"https://www.lidl.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"supermercados"},
    "lidl_pt_pt": {"name":"Lidl PT","base":"https://www.lidl.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"supermercados"},
    "lidl_nl_nl": {"name":"Lidl NL","base":"https://www.lidl.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"supermercados"},
    "lidl_be_be": {"name":"Lidl BE","base":"https://www.lidl.be","country":"BE","currency":"EUR","emoji":"🇧🇪","line":"supermercados"},
    "lidl_pl_pl": {"name":"Lidl PL","base":"https://www.lidl.pl","country":"PL","currency":"PLN","emoji":"🌐","line":"supermercados"},
    "aldi_de_de": {"name":"Aldi DE","base":"https://www.aldi.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"supermercados"},
    "aldi_us_us": {"name":"Aldi US","base":"https://www.aldi.us","country":"US","currency":"USD","emoji":"🇺🇸","line":"supermercados"},
    "aldi_gb_gb": {"name":"Aldi GB","base":"https://www.aldi.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"supermercados"},
    "aldi_fr_fr": {"name":"Aldi FR","base":"https://www.aldi.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"supermercados"},
    "aldi_es_es": {"name":"Aldi ES","base":"https://www.aldi.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"supermercados"},
    "aldi_it_it": {"name":"Aldi IT","base":"https://www.aldi.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"supermercados"},
    "aldi_nl_nl": {"name":"Aldi NL","base":"https://www.aldi.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"supermercados"},
    "tesco_gb_gb": {"name":"Tesco GB","base":"https://www.tesco.com","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"supermercados"},
    "tesco_ie_ie": {"name":"Tesco IE","base":"https://www.tesco.ie","country":"IE","currency":"EUR","emoji":"🌐","line":"supermercados"},
    "tesco_pl_pl": {"name":"Tesco PL","base":"https://www.tesco.pl","country":"PL","currency":"PLN","emoji":"🌐","line":"supermercados"},
    "tesco_cz_cz": {"name":"Tesco CZ","base":"https://www.tesco.cz","country":"CZ","currency":"CZK","emoji":"🌐","line":"supermercados"},
    "tesco_sk_sk": {"name":"Tesco SK","base":"https://www.tesco.sk","country":"SK","currency":"EUR","emoji":"🌐","line":"supermercados"},
    "tesco_hu_hu": {"name":"Tesco HU","base":"https://www.tesco.hu","country":"HU","currency":"HUF","emoji":"🌐","line":"supermercados"},
    "carrefour_it": {"name":"Carrefour IT","base":"https://www.carrefour.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"supermercados"},
    "soriana_mx": {"name":"Soriana","base":"https://www.soriana.com","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"supermercados"},
    "vivanda_pe": {"name":"Vivanda","base":"https://www.vivanda.com.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"supermercados"},
    "dia_ar": {"name":"Dia AR","base":"https://www.dia.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "vea_ar": {"name":"Vea AR","base":"https://www.vea.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "gpa_extra": {"name":"Extra BR","base":"https://www.extra.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "carulla_co": {"name":"Carulla","base":"https://www.carulla.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},
    "santaisabel_cl": {"name":"Santa Isabel CL","base":"https://www.santaisabel.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"supermercados"},
    "changomas_ar": {"name":"Changomas","base":"https://www.changomas.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"supermercados"},
    "mambo_br": {"name":"Mambo","base":"https://www.mambo.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"supermercados"},
    "surtimax_co": {"name":"Surtimax","base":"https://www.surtimax.com.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"supermercados"},

    # ── FARMACIAS ──
    "drogaraia": {"name":"Droga Raia","base":"https://www.drogaraia.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"farmacias"},
    "farmatodo_co": {"name":"Farmatodo","base":"https://www.farmatodo.com.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"farmacias"},
    "farmatodo_co_co": {"name":"Farmatodo CO","base":"https://www.farmatodo.com.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"farmacias"},
    "farmatodo_mx_mx": {"name":"Farmatodo MX","base":"https://www.farmatodo.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"farmacias"},
    "farmatodo_ve_ve": {"name":"Farmatodo VE","base":"https://www.farmatodo.com.ve","country":"VE","currency":"USD","emoji":"🌐","line":"farmacias"},
    "farmatodo_ar_ar": {"name":"Farmatodo AR","base":"https://www.farmatodo.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"farmacias"},
    "cruz_verde_co_co": {"name":"Cruz Verde CO","base":"https://www.cruzverde.com.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"farmacias"},
    "cruz_verde_cl_cl": {"name":"Cruz Verde CL","base":"https://www.cruzverde.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"farmacias"},
    "cruz_verde_pe_pe": {"name":"Cruz Verde PE","base":"https://www.cruzverde.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"farmacias"},
    "cruz_verde_mx_mx": {"name":"Cruz Verde MX","base":"https://www.cruzverde.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"farmacias"},
    "farmacias_guadalajara_mx_mx": {"name":"Farmacias Guadalajara MX","base":"https://www.farmaciasguadalajara.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"farmacias"},
    "farmacias_del_ahorro_mx_mx": {"name":"Farmacias del Ahorro MX","base":"https://www.farmaciasdelahorro.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"farmacias"},
    "drogasil": {"name":"Drogasil","base":"https://www.drogasil.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"farmacias"},
    "pacheco_br": {"name":"Drogaria Pacheco","base":"https://www.drogariaspacheco.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"farmacias"},
    "inkafarma_pe": {"name":"Inkafarma","base":"https://www.inkafarma.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"farmacias"},
    "boticasysalud_pe": {"name":"Boticas y Salud","base":"https://www.boticasysalud.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"farmacias"},

    # ── ELECTRO ──
    "magazineluiza": {"name":"Magazine Luiza","base":"https://www.magazineluiza.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "alkosto_co": {"name":"Alkosto","base":"https://www.alkosto.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"electro"},
    "samsung_br_br": {"name":"Samsung BR","base":"https://www.samsung.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "samsung_mx_mx": {"name":"Samsung MX","base":"https://www.samsung.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "samsung_ar_ar": {"name":"Samsung AR","base":"https://www.samsung.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "samsung_cl_cl": {"name":"Samsung CL","base":"https://www.samsung.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"electro"},
    "samsung_pe_pe": {"name":"Samsung PE","base":"https://www.samsung.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"electro"},
    "samsung_co_co": {"name":"Samsung CO","base":"https://www.samsung.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"electro"},
    "samsung_es_es": {"name":"Samsung ES","base":"https://www.samsung.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "samsung_fr_fr": {"name":"Samsung FR","base":"https://www.samsung.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"electro"},
    "samsung_it_it": {"name":"Samsung IT","base":"https://www.samsung.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "samsung_gb_gb": {"name":"Samsung GB","base":"https://www.samsung.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"electro"},
    "samsung_de_de": {"name":"Samsung DE","base":"https://www.samsung.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "samsung_us_us": {"name":"Samsung US","base":"https://www.samsung.us","country":"US","currency":"USD","emoji":"🇺🇸","line":"electro"},
    "samsung_pt_pt": {"name":"Samsung PT","base":"https://www.samsung.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"electro"},
    "lg_br_br": {"name":"LG BR","base":"https://www.lg.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "lg_mx_mx": {"name":"LG MX","base":"https://www.lg.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "lg_ar_ar": {"name":"LG AR","base":"https://www.lg.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "lg_cl_cl": {"name":"LG CL","base":"https://www.lg.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"electro"},
    "lg_es_es": {"name":"LG ES","base":"https://www.lg.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "lg_fr_fr": {"name":"LG FR","base":"https://www.lg.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"electro"},
    "lg_it_it": {"name":"LG IT","base":"https://www.lg.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "lg_de_de": {"name":"LG DE","base":"https://www.lg.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "lg_us_us": {"name":"LG US","base":"https://www.lg.us","country":"US","currency":"USD","emoji":"🇺🇸","line":"electro"},
    "lg_pt_pt": {"name":"LG PT","base":"https://www.lg.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"electro"},
    "motorola_br_br": {"name":"Motorola BR","base":"https://www.motorola.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "motorola_mx_mx": {"name":"Motorola MX","base":"https://www.motorola.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "motorola_ar_ar": {"name":"Motorola AR","base":"https://www.motorola.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "motorola_cl_cl": {"name":"Motorola CL","base":"https://www.motorola.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"electro"},
    "motorola_es_es": {"name":"Motorola ES","base":"https://www.motorola.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "motorola_it_it": {"name":"Motorola IT","base":"https://www.motorola.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "motorola_gb_gb": {"name":"Motorola GB","base":"https://www.motorola.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"electro"},
    "motorola_de_de": {"name":"Motorola DE","base":"https://www.motorola.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "motorola_us_us": {"name":"Motorola US","base":"https://www.motorola.com","country":"US","currency":"USD","emoji":"🇺🇸","line":"electro"},
    "electrolux_br_br": {"name":"Electrolux BR","base":"https://www.electrolux.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "electrolux_mx_mx": {"name":"Electrolux MX","base":"https://www.electrolux.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "electrolux_ar_ar": {"name":"Electrolux AR","base":"https://www.electrolux.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "electrolux_cl_cl": {"name":"Electrolux CL","base":"https://www.electrolux.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"electro"},
    "electrolux_es_es": {"name":"Electrolux ES","base":"https://www.electrolux.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "electrolux_it_it": {"name":"Electrolux IT","base":"https://www.electrolux.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "electrolux_fr_fr": {"name":"Electrolux FR","base":"https://www.electrolux.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"electro"},
    "electrolux_de_de": {"name":"Electrolux DE","base":"https://www.electrolux.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "electrolux_se_se": {"name":"Electrolux SE","base":"https://www.electrolux.se","country":"SE","currency":"SEK","emoji":"🌐","line":"electro"},
    "electrolux_pt_pt": {"name":"Electrolux PT","base":"https://www.electrolux.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"electro"},
    "electrolux_nl_nl": {"name":"Electrolux NL","base":"https://www.electrolux.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"electro"},
    "whirlpool_br_br": {"name":"Whirlpool BR","base":"https://www.whirlpool.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "whirlpool_mx_mx": {"name":"Whirlpool MX","base":"https://www.whirlpool.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "whirlpool_ar_ar": {"name":"Whirlpool AR","base":"https://www.whirlpool.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "whirlpool_es_es": {"name":"Whirlpool ES","base":"https://www.whirlpool.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "whirlpool_it_it": {"name":"Whirlpool IT","base":"https://www.whirlpool.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "whirlpool_fr_fr": {"name":"Whirlpool FR","base":"https://www.whirlpool.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"electro"},
    "whirlpool_de_de": {"name":"Whirlpool DE","base":"https://www.whirlpool.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "whirlpool_gb_gb": {"name":"Whirlpool GB","base":"https://www.whirlpool.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"electro"},
    "whirlpool_us_us": {"name":"Whirlpool US","base":"https://www.whirlpool.com","country":"US","currency":"USD","emoji":"🇺🇸","line":"electro"},
    "whirlpool_pt_pt": {"name":"Whirlpool PT","base":"https://www.whirlpool.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"electro"},
    "garbarino_ar_ar": {"name":"Garbarino AR","base":"https://www.garbarino.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "mediamarkt_es_es": {"name":"MediaMarkt ES","base":"https://www.mediamarkt.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"electro"},
    "mediamarkt_de_de": {"name":"MediaMarkt DE","base":"https://www.mediamarkt.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"electro"},
    "mediamarkt_it_it": {"name":"MediaMarkt IT","base":"https://www.mediamarkt.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"electro"},
    "mediamarkt_nl_nl": {"name":"MediaMarkt NL","base":"https://www.mediamarkt.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"electro"},
    "mediamarkt_pl_pl": {"name":"MediaMarkt PL","base":"https://www.mediamarkt.pl","country":"PL","currency":"PLN","emoji":"🌐","line":"electro"},
    "mediamarkt_pt_pt": {"name":"MediaMarkt PT","base":"https://www.mediamarkt.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"electro"},
    "mediamarkt_at_at": {"name":"MediaMarkt AT","base":"https://www.mediamarkt.at","country":"AT","currency":"EUR","emoji":"🌐","line":"electro"},
    "casas_bahia_br_br": {"name":"Casas Bahia BR","base":"https://www.casasbahia.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "ponto_frio_br_br": {"name":"Ponto Frio BR","base":"https://www.pontofrio.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "magazine_luiza_br_br": {"name":"Magazine Luiza BR","base":"https://www.magazineluiza.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "samsung_mx": {"name":"Samsung MX","base":"https://www.samsung.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"electro"},
    "fravega_ar": {"name":"Fravega","base":"https://www.fravega.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "samsung_br": {"name":"Samsung BR","base":"https://www.samsung.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "lg_br": {"name":"LG BR","base":"https://www.lg.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "casasbahia_br": {"name":"Casas Bahia","base":"https://www.casasbahia.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "alkomprar_co": {"name":"Alkomprar","base":"https://www.alkomprar.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"electro"},
    "musimundo_ar": {"name":"Musimundo","base":"https://www.musimundo.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"electro"},
    "pontofrio_br": {"name":"Ponto Frio","base":"https://www.pontofrio.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "motorola_br": {"name":"Motorola BR","base":"https://www.motorola.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "electrolux_br": {"name":"Electrolux BR","base":"https://www.electrolux.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},
    "whirlpool_br": {"name":"Whirlpool BR","base":"https://www.whirlpool.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"electro"},

    # ── DEPORTES ──
    "centauro": {"name":"Centauro BR","base":"https://www.centauro.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "decathlon_fr": {"name":"Decathlon FR","base":"https://www.decathlon.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"deportes"},
    "decathlon_es": {"name":"Decathlon ES","base":"https://www.decathlon.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"deportes"},
    "decathlon_it": {"name":"Decathlon IT","base":"https://www.decathlon.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"deportes"},
    "decathlon_pt": {"name":"Decathlon PT","base":"https://www.decathlon.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"deportes"},
    "decathlon_cl": {"name":"Decathlon CL","base":"https://www.decathlon.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"deportes"},
    "decathlon_fr_fr": {"name":"Decathlon FR","base":"https://www.decathlon.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"deportes"},
    "decathlon_es_es": {"name":"Decathlon ES","base":"https://www.decathlon.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"deportes"},
    "decathlon_it_it": {"name":"Decathlon IT","base":"https://www.decathlon.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"deportes"},
    "decathlon_de_de": {"name":"Decathlon DE","base":"https://www.decathlon.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"deportes"},
    "decathlon_gb_gb": {"name":"Decathlon GB","base":"https://www.decathlon.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"deportes"},
    "decathlon_pt_pt": {"name":"Decathlon PT","base":"https://www.decathlon.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"deportes"},
    "decathlon_nl_nl": {"name":"Decathlon NL","base":"https://www.decathlon.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"deportes"},
    "decathlon_be_be": {"name":"Decathlon BE","base":"https://www.decathlon.be","country":"BE","currency":"EUR","emoji":"🇧🇪","line":"deportes"},
    "decathlon_pl_pl": {"name":"Decathlon PL","base":"https://www.decathlon.pl","country":"PL","currency":"PLN","emoji":"🌐","line":"deportes"},
    "decathlon_br_br": {"name":"Decathlon BR","base":"https://www.decathlon.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "decathlon_cl_cl": {"name":"Decathlon CL","base":"https://www.decathlon.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"deportes"},
    "decathlon_pe_pe": {"name":"Decathlon PE","base":"https://www.decathlon.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"deportes"},
    "decathlon_co_co": {"name":"Decathlon CO","base":"https://www.decathlon.com.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"deportes"},
    "decathlon_ar_ar": {"name":"Decathlon AR","base":"https://www.decathlon.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"deportes"},
    "decathlon_mx_mx": {"name":"Decathlon MX","base":"https://www.decathlon.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "decathlon_se_se": {"name":"Decathlon SE","base":"https://www.decathlon.se","country":"SE","currency":"SEK","emoji":"🌐","line":"deportes"},
    "nike_br_br": {"name":"Nike BR","base":"https://www.nike.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "nike_mx_mx": {"name":"Nike MX","base":"https://www.nike.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "nike_ar_ar": {"name":"Nike AR","base":"https://www.nike.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"deportes"},
    "nike_cl_cl": {"name":"Nike CL","base":"https://www.nike.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"deportes"},
    "nike_pe_pe": {"name":"Nike PE","base":"https://www.nike.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"deportes"},
    "nike_co_co": {"name":"Nike CO","base":"https://www.nike.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"deportes"},
    "nike_es_es": {"name":"Nike ES","base":"https://www.nike.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"deportes"},
    "nike_fr_fr": {"name":"Nike FR","base":"https://www.nike.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"deportes"},
    "nike_it_it": {"name":"Nike IT","base":"https://www.nike.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"deportes"},
    "nike_de_de": {"name":"Nike DE","base":"https://www.nike.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"deportes"},
    "nike_gb_gb": {"name":"Nike GB","base":"https://www.nike.com","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"deportes"},
    "nike_pt_pt": {"name":"Nike PT","base":"https://www.nike.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"deportes"},
    "nike_nl_nl": {"name":"Nike NL","base":"https://www.nike.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"deportes"},
    "nike_se_se": {"name":"Nike SE","base":"https://www.nike.se","country":"SE","currency":"SEK","emoji":"🌐","line":"deportes"},
    "nike_pl_pl": {"name":"Nike PL","base":"https://www.nike.pl","country":"PL","currency":"PLN","emoji":"🌐","line":"deportes"},
    "adidas_br_br": {"name":"Adidas BR","base":"https://www.adidas.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "adidas_mx_mx": {"name":"Adidas MX","base":"https://www.adidas.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "adidas_ar_ar": {"name":"Adidas AR","base":"https://www.adidas.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"deportes"},
    "adidas_cl_cl": {"name":"Adidas CL","base":"https://www.adidas.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"deportes"},
    "adidas_pe_pe": {"name":"Adidas PE","base":"https://www.adidas.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"deportes"},
    "adidas_co_co": {"name":"Adidas CO","base":"https://www.adidas.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"deportes"},
    "adidas_es_es": {"name":"Adidas ES","base":"https://www.adidas.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"deportes"},
    "adidas_fr_fr": {"name":"Adidas FR","base":"https://www.adidas.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"deportes"},
    "adidas_it_it": {"name":"Adidas IT","base":"https://www.adidas.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"deportes"},
    "adidas_de_de": {"name":"Adidas DE","base":"https://www.adidas.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"deportes"},
    "adidas_gb_gb": {"name":"Adidas GB","base":"https://www.adidas.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"deportes"},
    "adidas_pt_pt": {"name":"Adidas PT","base":"https://www.adidas.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"deportes"},
    "adidas_nl_nl": {"name":"Adidas NL","base":"https://www.adidas.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"deportes"},
    "adidas_pl_pl": {"name":"Adidas PL","base":"https://www.adidas.pl","country":"PL","currency":"PLN","emoji":"🌐","line":"deportes"},
    "adidas_se_se": {"name":"Adidas SE","base":"https://www.adidas.se","country":"SE","currency":"SEK","emoji":"🌐","line":"deportes"},
    "puma_br_br": {"name":"Puma BR","base":"https://www.puma.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "puma_mx_mx": {"name":"Puma MX","base":"https://www.puma.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "puma_ar_ar": {"name":"Puma AR","base":"https://www.puma.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"deportes"},
    "puma_es_es": {"name":"Puma ES","base":"https://www.puma.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"deportes"},
    "puma_fr_fr": {"name":"Puma FR","base":"https://www.puma.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"deportes"},
    "puma_it_it": {"name":"Puma IT","base":"https://www.puma.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"deportes"},
    "puma_de_de": {"name":"Puma DE","base":"https://www.puma.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"deportes"},
    "puma_gb_gb": {"name":"Puma GB","base":"https://www.puma.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"deportes"},
    "puma_pt_pt": {"name":"Puma PT","base":"https://www.puma.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"deportes"},
    "puma_nl_nl": {"name":"Puma NL","base":"https://www.puma.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"deportes"},
    "centauro_br_br": {"name":"Centauro BR","base":"https://www.centauro.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "netshoes_br_br": {"name":"Netshoes BR","base":"https://www.netshoes.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "nike_br": {"name":"Nike BR","base":"https://www.nike.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "adidas_br": {"name":"Adidas BR","base":"https://www.adidas.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "decathlon_br": {"name":"Decathlon BR","base":"https://www.decathlon.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"deportes"},
    "decathlon_uk": {"name":"Decathlon UK","base":"https://www.decathlon.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"deportes"},
    "marti_mx": {"name":"Marti","base":"https://www.marti.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "decathlon_co": {"name":"Decathlon CO","base":"https://www.decathlon.com.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"deportes"},
    "decathlon_ar": {"name":"Decathlon AR","base":"https://www.decathlon.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"deportes"},
    "decathlon_mx": {"name":"Decathlon MX","base":"https://www.decathlon.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"deportes"},
    "decathlon_pe": {"name":"Decathlon PE","base":"https://www.decathlon.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"deportes"},

    # ── HOGAR ──
    "sodimac_co_co": {"name":"Sodimac CO","base":"https://www.sodimac.com.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"hogar"},
    "sodimac_cl_cl": {"name":"Sodimac CL","base":"https://www.sodimac.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"hogar"},
    "sodimac_pe_pe": {"name":"Sodimac PE","base":"https://www.sodimac.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"hogar"},
    "sodimac_ar_ar": {"name":"Sodimac AR","base":"https://www.sodimac.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"hogar"},
    "sodimac_br_br": {"name":"Sodimac BR","base":"https://www.sodimac.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"hogar"},
    "sodimac_mx_mx": {"name":"Sodimac MX","base":"https://www.sodimac.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"hogar"},
    "sodimac_uy_uy": {"name":"Sodimac UY","base":"https://www.sodimac.com.uy","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"hogar"},
    "easy_ar_ar": {"name":"Easy AR","base":"https://www.easy.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"hogar"},
    "easy_cl_cl": {"name":"Easy CL","base":"https://www.easy.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"hogar"},
    "easy_co_co": {"name":"Easy CO","base":"https://www.easy.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"hogar"},
    "easy_pe_pe": {"name":"Easy PE","base":"https://www.easy.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"hogar"},
    "leroy_merlin_br_br": {"name":"Leroy Merlin BR","base":"https://www.leroymerlin.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"hogar"},
    "leroy_merlin_es_es": {"name":"Leroy Merlin ES","base":"https://www.leroymerlin.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"hogar"},
    "leroy_merlin_fr_fr": {"name":"Leroy Merlin FR","base":"https://www.leroymerlin.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"hogar"},
    "leroy_merlin_it_it": {"name":"Leroy Merlin IT","base":"https://www.leroymerlin.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"hogar"},
    "leroy_merlin_pt_pt": {"name":"Leroy Merlin PT","base":"https://www.leroymerlin.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"hogar"},
    "leroy_merlin_pl_pl": {"name":"Leroy Merlin PL","base":"https://www.leroymerlin.pl","country":"PL","currency":"PLN","emoji":"🌐","line":"hogar"},
    "leroy_merlin_ro_ro": {"name":"Leroy Merlin RO","base":"https://www.leroymerlin.ro","country":"RO","currency":"RON","emoji":"🇷🇴","line":"hogar"},
    "rosen_cl_cl": {"name":"Rosen CL","base":"https://www.rosen.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"hogar"},
    "rosen_pe_pe": {"name":"Rosen PE","base":"https://www.rosen.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"hogar"},
    "rosen_co_co": {"name":"Rosen CO","base":"https://www.rosen.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"hogar"},
    "rosen_mx_mx": {"name":"Rosen MX","base":"https://www.rosen.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"hogar"},
    "rosen_ar_ar": {"name":"Rosen AR","base":"https://www.rosen.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"hogar"},
    "rosen_ec_ec": {"name":"Rosen EC","base":"https://www.rosen.com","country":"EC","currency":"USD","emoji":"🇪🇨","line":"hogar"},
    "ikea_es_es": {"name":"IKEA ES","base":"https://www.ikea.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"hogar"},
    "ikea_fr_fr": {"name":"IKEA FR","base":"https://www.ikea.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"hogar"},
    "ikea_it_it": {"name":"IKEA IT","base":"https://www.ikea.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"hogar"},
    "ikea_de_de": {"name":"IKEA DE","base":"https://www.ikea.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"hogar"},
    "ikea_gb_gb": {"name":"IKEA GB","base":"https://www.ikea.com","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"hogar"},
    "ikea_pt_pt": {"name":"IKEA PT","base":"https://www.ikea.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"hogar"},
    "ikea_nl_nl": {"name":"IKEA NL","base":"https://www.ikea.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"hogar"},
    "ikea_be_be": {"name":"IKEA BE","base":"https://www.ikea.be","country":"BE","currency":"EUR","emoji":"🇧🇪","line":"hogar"},
    "ikea_pl_pl": {"name":"IKEA PL","base":"https://www.ikea.pl","country":"PL","currency":"PLN","emoji":"🌐","line":"hogar"},
    "mobly_br_br": {"name":"Mobly BR","base":"https://www.mobly.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"hogar"},
    "homecenter": {"name":"Homecenter CO","base":"https://www.homecenter.com.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"hogar"},
    "sodimac_cl": {"name":"Sodimac CL","base":"https://www.sodimac.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"hogar"},
    "easy_ar": {"name":"Easy AR","base":"https://www.easy.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"hogar"},
    "leroymerlin_br": {"name":"Leroy Merlin BR","base":"https://www.leroymerlin.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"hogar"},
    "sodimac_co": {"name":"Sodimac CO","base":"https://www.sodimac.com.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"hogar"},
    "promart_pe": {"name":"Promart","base":"https://www.promart.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"hogar"},
    "rosen_cl": {"name":"Rosen CL","base":"https://www.rosen.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"hogar"},

    # ── DEPARTAMENTALES ──
    "ripley_cl_cl": {"name":"Ripley CL","base":"https://www.ripley.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"departamentales"},
    "ripley_pe_pe": {"name":"Ripley PE","base":"https://www.ripley.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"departamentales"},
    "ripley_co_co": {"name":"Ripley CO","base":"https://www.ripley.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"departamentales"},
    "ripley_mx_mx": {"name":"Ripley MX","base":"https://www.ripley.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "ripley_ar_ar": {"name":"Ripley AR","base":"https://www.ripley.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"departamentales"},
    "falabella_cl_cl": {"name":"Falabella CL","base":"https://www.falabella.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"departamentales"},
    "falabella_pe_pe": {"name":"Falabella PE","base":"https://www.falabella.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"departamentales"},
    "falabella_co_co": {"name":"Falabella CO","base":"https://www.falabella.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"departamentales"},
    "falabella_ar_ar": {"name":"Falabella AR","base":"https://www.falabella.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"departamentales"},
    "falabella_br_br": {"name":"Falabella BR","base":"https://www.falabella.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"departamentales"},
    "falabella_mx_mx": {"name":"Falabella MX","base":"https://www.falabella.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "falabella_uy_uy": {"name":"Falabella UY","base":"https://www.falabella.com.uy","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"departamentales"},
    "coppel_mx_mx": {"name":"Coppel MX","base":"https://www.coppel.com","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "coppel_ar_ar": {"name":"Coppel AR","base":"https://www.coppel.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"departamentales"},
    "liverpool_mx": {"name":"Liverpool","base":"https://www.liverpool.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "palacio_mx": {"name":"Palacio Hierro","base":"https://www.elpalaciodehierro.com","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "paris_cl": {"name":"Paris CL","base":"https://www.paris.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"departamentales"},
    "sears_mx": {"name":"Sears MX","base":"https://www.sears.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "oechsle_pe": {"name":"Oechsle","base":"https://www.oechsle.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"departamentales"},
    "sanborns_mx": {"name":"Sanborns","base":"https://www.sanborns.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"departamentales"},
    "lapolar_cl": {"name":"La Polar CL","base":"https://www.lapolar.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"departamentales"},

    # ── MODA ──
    "ca_br_br": {"name":"C&A BR","base":"https://www.cea.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "ca_mx_mx": {"name":"C&A MX","base":"https://www.cea.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "ca_ar_ar": {"name":"C&A AR","base":"https://www.cea.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "ca_cl_cl": {"name":"C&A CL","base":"https://www.cea.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"moda"},
    "ca_pe_pe": {"name":"C&A PE","base":"https://www.cea.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "ca_co_co": {"name":"C&A CO","base":"https://www.cea.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "ca_es_es": {"name":"C&A ES","base":"https://www.cea.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"moda"},
    "ca_fr_fr": {"name":"C&A FR","base":"https://www.cea.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"moda"},
    "ca_de_de": {"name":"C&A DE","base":"https://www.cea.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"moda"},
    "ca_it_it": {"name":"C&A IT","base":"https://www.cea.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"moda"},
    "ca_pt_pt": {"name":"C&A PT","base":"https://www.cea.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"moda"},
    "ca_nl_nl": {"name":"C&A NL","base":"https://www.cea.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"moda"},
    "hering_br_br": {"name":"Hering BR","base":"https://www.hering.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "hering_mx_mx": {"name":"Hering MX","base":"https://www.hering.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "hering_ar_ar": {"name":"Hering AR","base":"https://www.hering.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "hering_cl_cl": {"name":"Hering CL","base":"https://www.hering.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"moda"},
    "hering_pe_pe": {"name":"Hering PE","base":"https://www.hering.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "hering_co_co": {"name":"Hering CO","base":"https://www.hering.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "zara_es_es": {"name":"Zara ES","base":"https://www.zara.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"moda"},
    "zara_fr_fr": {"name":"Zara FR","base":"https://www.zara.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"moda"},
    "zara_it_it": {"name":"Zara IT","base":"https://www.zara.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"moda"},
    "zara_de_de": {"name":"Zara DE","base":"https://www.zara.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"moda"},
    "zara_gb_gb": {"name":"Zara GB","base":"https://www.zara.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"moda"},
    "zara_pt_pt": {"name":"Zara PT","base":"https://www.zara.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"moda"},
    "zara_nl_nl": {"name":"Zara NL","base":"https://www.zara.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"moda"},
    "zara_cl_cl": {"name":"Zara CL","base":"https://www.zara.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"moda"},
    "zara_mx_mx": {"name":"Zara MX","base":"https://www.zara.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "zara_ar_ar": {"name":"Zara AR","base":"https://www.zara.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "zara_co_co": {"name":"Zara CO","base":"https://www.zara.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "zara_pe_pe": {"name":"Zara PE","base":"https://www.zara.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "zara_br_br": {"name":"Zara BR","base":"https://www.zara.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "mango_es_es": {"name":"Mango ES","base":"https://www.mango.com","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"moda"},
    "mango_fr_fr": {"name":"Mango FR","base":"https://www.mango.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"moda"},
    "mango_it_it": {"name":"Mango IT","base":"https://www.mango.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"moda"},
    "mango_de_de": {"name":"Mango DE","base":"https://www.mango.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"moda"},
    "mango_gb_gb": {"name":"Mango GB","base":"https://www.mango.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"moda"},
    "mango_pt_pt": {"name":"Mango PT","base":"https://www.mango.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"moda"},
    "mango_nl_nl": {"name":"Mango NL","base":"https://www.mango.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"moda"},
    "leonisa_co_co": {"name":"Leonisa CO","base":"https://www.leonisa.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "leonisa_pe_pe": {"name":"Leonisa PE","base":"https://www.leonisa.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "leonisa_mx_mx": {"name":"Leonisa MX","base":"https://www.leonisa.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "leonisa_es_es": {"name":"Leonisa ES","base":"https://www.leonisa.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"moda"},
    "leonisa_us_us": {"name":"Leonisa US","base":"https://www.leonisa.com","country":"US","currency":"USD","emoji":"🇺🇸","line":"moda"},
    "totto_co_co": {"name":"Totto CO","base":"https://www.totto.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "totto_pe_pe": {"name":"Totto PE","base":"https://www.totto.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "totto_ec_ec": {"name":"Totto EC","base":"https://www.totto.com","country":"EC","currency":"USD","emoji":"🇪🇨","line":"moda"},
    "totto_mx_mx": {"name":"Totto MX","base":"https://www.totto.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "totto_cr_cr": {"name":"Totto CR","base":"https://www.totto.co.cr","country":"CR","currency":"CRC","emoji":"🇨🇷","line":"moda"},
    "totto_gt_gt": {"name":"Totto GT","base":"https://www.totto.com.gt","country":"GT","currency":"GTQ","emoji":"🌐","line":"moda"},
    "totto_pa_pa": {"name":"Totto PA","base":"https://www.totto.com.pa","country":"PA","currency":"USD","emoji":"🇵🇦","line":"moda"},
    "totto_bo_bo": {"name":"Totto BO","base":"https://www.totto.com.bo","country":"BO","currency":"BOB","emoji":"🌐","line":"moda"},
    "hm_es_es": {"name":"H&M ES","base":"https://www.hm.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"moda"},
    "hm_fr_fr": {"name":"H&M FR","base":"https://www.hm.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"moda"},
    "hm_it_it": {"name":"H&M IT","base":"https://www.hm.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"moda"},
    "hm_de_de": {"name":"H&M DE","base":"https://www.hm.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"moda"},
    "hm_gb_gb": {"name":"H&M GB","base":"https://www.hm.com","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"moda"},
    "hm_pt_pt": {"name":"H&M PT","base":"https://www.hm.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"moda"},
    "hm_nl_nl": {"name":"H&M NL","base":"https://www.hm.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"moda"},
    "hm_cl_cl": {"name":"H&M CL","base":"https://www.hm.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"moda"},
    "hm_mx_mx": {"name":"H&M MX","base":"https://www.hm.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "hm_ar_ar": {"name":"H&M AR","base":"https://www.hm.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "hm_pe_pe": {"name":"H&M PE","base":"https://www.hm.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "hm_co_co": {"name":"H&M CO","base":"https://www.hm.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "hm_br_br": {"name":"H&M BR","base":"https://www.hm.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "marisa_br_br": {"name":"Marisa BR","base":"https://www.marisa.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "marisa_ar_ar": {"name":"Marisa AR","base":"https://www.marisa.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "riachuelo_br_br": {"name":"Riachuelo BR","base":"https://www.riachuelo.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "dafiti_br_br": {"name":"Dafiti BR","base":"https://www.dafiti.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "dafiti_mx_mx": {"name":"Dafiti MX","base":"https://www.dafiti.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "dafiti_ar_ar": {"name":"Dafiti AR","base":"https://www.dafiti.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"moda"},
    "dafiti_cl_cl": {"name":"Dafiti CL","base":"https://www.dafiti.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"moda"},
    "dafiti_co_co": {"name":"Dafiti CO","base":"https://www.dafiti.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "dafiti_pe_pe": {"name":"Dafiti PE","base":"https://www.dafiti.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"moda"},
    "renner": {"name":"Lojas Renner","base":"https://www.lojasrenner.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "ca_mx": {"name":"C&A MX","base":"https://www.cea.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"moda"},
    "ca_br": {"name":"C&A BR","base":"https://www.cea.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "marisa_br": {"name":"Marisa","base":"https://www.marisa.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "riachuelo_br": {"name":"Riachuelo","base":"https://www.riachuelo.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"moda"},
    "arturocalle_co": {"name":"Arturo Calle","base":"https://www.arturocalle.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "leonisa_co": {"name":"Leonisa","base":"https://www.leonisa.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},
    "totto_co": {"name":"Totto","base":"https://www.totto.com","country":"CO","currency":"COP","emoji":"🇨🇴","line":"moda"},

    # ── BELLEZA ──
    "o_boticario_br_br": {"name":"O Boticário BR","base":"https://www.oboticario.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "o_boticario_pt_pt": {"name":"O Boticário PT","base":"https://www.oboticario.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"belleza"},
    "o_boticario_ar_ar": {"name":"O Boticário AR","base":"https://www.oboticario.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"belleza"},
    "o_boticario_cl_cl": {"name":"O Boticário CL","base":"https://www.oboticario.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"belleza"},
    "o_boticario_pe_pe": {"name":"O Boticário PE","base":"https://www.oboticario.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"belleza"},
    "o_boticario_co_co": {"name":"O Boticário CO","base":"https://www.oboticario.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"belleza"},
    "o_boticario_mx_mx": {"name":"O Boticário MX","base":"https://www.oboticario.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "o_boticario_bo_bo": {"name":"O Boticário BO","base":"https://www.oboticario.com.bo","country":"BO","currency":"BOB","emoji":"🌐","line":"belleza"},
    "o_boticario_py_py": {"name":"O Boticário PY","base":"https://www.oboticario.com.py","country":"PY","currency":"PYG","emoji":"🌐","line":"belleza"},
    "o_boticario_uy_uy": {"name":"O Boticário UY","base":"https://www.oboticario.com.uy","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"belleza"},
    "o_boticario_es_es": {"name":"O Boticário ES","base":"https://www.oboticario.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"belleza"},
    "o_boticario_fr_fr": {"name":"O Boticário FR","base":"https://www.oboticario.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"belleza"},
    "o_boticario_it_it": {"name":"O Boticário IT","base":"https://www.oboticario.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"belleza"},
    "o_boticario_de_de": {"name":"O Boticário DE","base":"https://www.oboticario.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"belleza"},
    "o_boticario_gb_gb": {"name":"O Boticário GB","base":"https://www.oboticario.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"belleza"},
    "o_boticario_us_us": {"name":"O Boticário US","base":"https://www.oboticario.com","country":"US","currency":"USD","emoji":"🇺🇸","line":"belleza"},
    "natura_br_br": {"name":"Natura BR","base":"https://www.natura.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "natura_mx_mx": {"name":"Natura MX","base":"https://www.natura.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "natura_ar_ar": {"name":"Natura AR","base":"https://www.natura.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"belleza"},
    "natura_cl_cl": {"name":"Natura CL","base":"https://www.natura.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"belleza"},
    "natura_pe_pe": {"name":"Natura PE","base":"https://www.natura.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"belleza"},
    "natura_co_co": {"name":"Natura CO","base":"https://www.natura.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"belleza"},
    "natura_bo_bo": {"name":"Natura BO","base":"https://www.natura.com.bo","country":"BO","currency":"BOB","emoji":"🌐","line":"belleza"},
    "natura_fr_fr": {"name":"Natura FR","base":"https://www.natura.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"belleza"},
    "avon_br_br": {"name":"Avon BR","base":"https://www.avon.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "avon_mx_mx": {"name":"Avon MX","base":"https://www.avon.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "avon_ar_ar": {"name":"Avon AR","base":"https://www.avon.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"belleza"},
    "avon_cl_cl": {"name":"Avon CL","base":"https://www.avon.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"belleza"},
    "avon_es_es": {"name":"Avon ES","base":"https://www.avon.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"belleza"},
    "avon_fr_fr": {"name":"Avon FR","base":"https://www.avon.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"belleza"},
    "avon_it_it": {"name":"Avon IT","base":"https://www.avon.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"belleza"},
    "avon_de_de": {"name":"Avon DE","base":"https://www.avon.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"belleza"},
    "avon_gb_gb": {"name":"Avon GB","base":"https://www.avon.com","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"belleza"},
    "avon_pt_pt": {"name":"Avon PT","base":"https://www.avon.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"belleza"},
    "avon_pl_pl": {"name":"Avon PL","base":"https://www.avon.pl","country":"PL","currency":"PLN","emoji":"🌐","line":"belleza"},
    "sephora_br_br": {"name":"Sephora BR","base":"https://www.sephora.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "sephora_mx_mx": {"name":"Sephora MX","base":"https://www.sephora.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "sephora_es_es": {"name":"Sephora ES","base":"https://www.sephora.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"belleza"},
    "sephora_fr_fr": {"name":"Sephora FR","base":"https://www.sephora.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"belleza"},
    "sephora_it_it": {"name":"Sephora IT","base":"https://www.sephora.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"belleza"},
    "sephora_de_de": {"name":"Sephora DE","base":"https://www.sephora.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"belleza"},
    "sephora_gb_gb": {"name":"Sephora GB","base":"https://www.sephora.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"belleza"},
    "sephora_pt_pt": {"name":"Sephora PT","base":"https://www.sephora.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"belleza"},
    "mac_br_br": {"name":"MAC BR","base":"https://www.maccosmetics.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "mac_mx_mx": {"name":"MAC MX","base":"https://www.maccosmetics.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "mac_ar_ar": {"name":"MAC AR","base":"https://www.maccosmetics.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"belleza"},
    "mac_es_es": {"name":"MAC ES","base":"https://www.maccosmetics.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"belleza"},
    "mac_fr_fr": {"name":"MAC FR","base":"https://www.maccosmetics.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"belleza"},
    "mac_it_it": {"name":"MAC IT","base":"https://www.maccosmetics.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"belleza"},
    "mac_de_de": {"name":"MAC DE","base":"https://www.maccosmetics.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"belleza"},
    "mac_gb_gb": {"name":"MAC GB","base":"https://www.maccosmetics.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"belleza"},
    "mac_pt_pt": {"name":"MAC PT","base":"https://www.maccosmetics.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"belleza"},
    "oboticario_br": {"name":"O Boticario","base":"https://www.oboticario.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "natura_br": {"name":"Natura BR","base":"https://www.natura.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "natura_mx": {"name":"Natura MX","base":"https://www.natura.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"belleza"},
    "natura_co": {"name":"Natura CO","base":"https://www.natura.com.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"belleza"},
    "avon_br": {"name":"Avon BR","base":"https://www.avon.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"belleza"},
    "natura_cl": {"name":"Natura CL","base":"https://www.natura.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"belleza"},

    # ── ALIMENTOS ──
    "nestle_br_br": {"name":"Nestlé BR","base":"https://www.nestle.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "nestle_mx_mx": {"name":"Nestlé MX","base":"https://www.nestle.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"alimentos"},
    "nestle_ar_ar": {"name":"Nestlé AR","base":"https://www.nestle.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"alimentos"},
    "nestle_es_es": {"name":"Nestlé ES","base":"https://www.nestle.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"alimentos"},
    "nestle_fr_fr": {"name":"Nestlé FR","base":"https://www.nestle.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"alimentos"},
    "nestle_it_it": {"name":"Nestlé IT","base":"https://www.nestle.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"alimentos"},
    "nestle_de_de": {"name":"Nestlé DE","base":"https://www.nestle.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"alimentos"},
    "nestle_pt_pt": {"name":"Nestlé PT","base":"https://www.nestle.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"alimentos"},
    "nestle_cl_cl": {"name":"Nestlé CL","base":"https://www.nestle.cl","country":"CL","currency":"CLP","emoji":"🇨🇱","line":"alimentos"},
    "nestle_co_co": {"name":"Nestlé CO","base":"https://www.nestle.co","country":"CO","currency":"COP","emoji":"🇨🇴","line":"alimentos"},
    "nestle_pe_pe": {"name":"Nestlé PE","base":"https://www.nestle.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"alimentos"},
    "nestle_gb_gb": {"name":"Nestlé GB","base":"https://www.nestle.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"alimentos"},
    "unilever_br_br": {"name":"Unilever BR","base":"https://www.unilever.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "unilever_mx_mx": {"name":"Unilever MX","base":"https://www.unilever.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"alimentos"},
    "unilever_ar_ar": {"name":"Unilever AR","base":"https://www.unilever.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"alimentos"},
    "unilever_es_es": {"name":"Unilever ES","base":"https://www.unilever.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"alimentos"},
    "unilever_fr_fr": {"name":"Unilever FR","base":"https://www.unilever.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"alimentos"},
    "unilever_it_it": {"name":"Unilever IT","base":"https://www.unilever.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"alimentos"},
    "unilever_de_de": {"name":"Unilever DE","base":"https://www.unilever.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"alimentos"},
    "unilever_gb_gb": {"name":"Unilever GB","base":"https://www.unilever.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"alimentos"},
    "unilever_pt_pt": {"name":"Unilever PT","base":"https://www.unilever.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"alimentos"},
    "unilever_nl_nl": {"name":"Unilever NL","base":"https://www.unilever.nl","country":"NL","currency":"EUR","emoji":"🌐","line":"alimentos"},
    "danone_br_br": {"name":"Danone BR","base":"https://www.danone.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "danone_mx_mx": {"name":"Danone MX","base":"https://www.danone.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"alimentos"},
    "danone_ar_ar": {"name":"Danone AR","base":"https://www.danone.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"alimentos"},
    "danone_es_es": {"name":"Danone ES","base":"https://www.danone.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"alimentos"},
    "danone_fr_fr": {"name":"Danone FR","base":"https://www.danone.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"alimentos"},
    "danone_it_it": {"name":"Danone IT","base":"https://www.danone.it","country":"IT","currency":"EUR","emoji":"🇮🇹","line":"alimentos"},
    "danone_de_de": {"name":"Danone DE","base":"https://www.danone.de","country":"DE","currency":"EUR","emoji":"🇩🇪","line":"alimentos"},
    "danone_pt_pt": {"name":"Danone PT","base":"https://www.danone.pt","country":"PT","currency":"EUR","emoji":"🇵🇹","line":"alimentos"},
    "swift_br_br": {"name":"Swift BR","base":"https://www.swift.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "swift_ar_ar": {"name":"Swift AR","base":"https://www.swift.com.ar","country":"AR","currency":"ARS","emoji":"🇦🇷","line":"alimentos"},
    "swift_uy_uy": {"name":"Swift UY","base":"https://www.swift.com.uy","country":"UY","currency":"UYU","emoji":"🇺🇾","line":"alimentos"},
    "nestle_br": {"name":"Nestle BR","base":"https://www.nestle.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "unilever_br": {"name":"Unilever BR","base":"https://www.unilever.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},
    "swift_br": {"name":"Swift BR","base":"https://www.swift.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"alimentos"},

    # ── LIBRERIA ──
    "office_depot_mx_mx": {"name":"Office Depot MX","base":"https://www.officedepot.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"libreria"},
    "office_depot_es_es": {"name":"Office Depot ES","base":"https://www.officedepot.es","country":"ES","currency":"EUR","emoji":"🇪🇸","line":"libreria"},
    "office_depot_fr_fr": {"name":"Office Depot FR","base":"https://www.officedepot.fr","country":"FR","currency":"EUR","emoji":"🇫🇷","line":"libreria"},
    "office_depot_gb_gb": {"name":"Office Depot GB","base":"https://www.officedepot.co.uk","country":"GB","currency":"GBP","emoji":"🇬🇧","line":"libreria"},
    "office_depot_us_us": {"name":"Office Depot US","base":"https://www.officedepot.com","country":"US","currency":"USD","emoji":"🇺🇸","line":"libreria"},
    "office_depot_pe_pe": {"name":"Office Depot PE","base":"https://www.officedepot.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"libreria"},
    "saraiva_br_br": {"name":"Saraiva BR","base":"https://www.saraiva.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"libreria"},
    "livraria_cultura_br_br": {"name":"Livraria Cultura BR","base":"https://www.livrariacultura.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"libreria"},
    "saraiva_br": {"name":"Saraiva","base":"https://www.saraiva.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"libreria"},
    "officedepot_mx": {"name":"Office Depot MX","base":"https://www.officedepot.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"libreria"},
    "tailoy_pe": {"name":"Tai Loy","base":"https://www.tailoy.com.pe","country":"PE","currency":"PEN","emoji":"🇵🇪","line":"libreria"},

    # ── AUTOPARTES ──
    "autozone_mx_mx": {"name":"AutoZone MX","base":"https://www.autozone.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"autopartes"},
    "autozone_us_us": {"name":"AutoZone US","base":"https://www.autozone.com","country":"US","currency":"USD","emoji":"🇺🇸","line":"autopartes"},
    "autozone_br_br": {"name":"AutoZone BR","base":"https://www.autozone.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"autopartes"},
    "autozone_mx": {"name":"AutoZone MX","base":"https://www.autozone.com.mx","country":"MX","currency":"MXN","emoji":"🇲🇽","line":"autopartes"},

    # ── MASCOTAS ──
    "petlove_br_br": {"name":"Petlove BR","base":"https://www.petlove.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
    "petz_br_br": {"name":"Petz BR","base":"https://www.petz.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
    "cobasi_br_br": {"name":"Cobasi BR","base":"https://www.cobasi.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
    "petlove_br": {"name":"Petlove","base":"https://www.petlove.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
    "petz_br": {"name":"Petz","base":"https://www.petz.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
    "cobasi_br": {"name":"Cobasi","base":"https://www.cobasi.com.br","country":"BR","currency":"BRL","emoji":"🇧🇷","line":"mascotas"},
}

