// AUTO-GENERATED — do not edit. Run: python3 ops/sync_market_stats.py

export const MARKET_STATS = {
  retailersDefined: 81,
  retailersVerified: 41,
  platforms: 4,
  platformVtex: 51,
  platformShopify: 15,
  platformMagento: 7,
  platformWooCommerce: 2,
  woocommerceStores: ["Nuna Org\u00e1nica", "Xray Chipped PE"],
  countries: 8,
  countryCodes: ['AR', 'BR', 'CL', 'CO', 'FR', 'IT', 'MX', 'PE'],
  mcpTools: 27,
  mcpToolsLegacy: 49,
  mcpToolsFull: 46,
  mcpDefaultProfile: "default",
  mcpBundles: {"shop": [{"id": "market_discover", "description": "Retail coverage in one call: business lines, retailers, and countries. Replaces market_lines + market_stores + market_countries. 41 verified retailers across 8 countries.", "canonical": true}, {"id": "market_add", "description": "Add to cart. Copy ALL four fields from market_search: product_id, name, price, store (use store_key value as store). Missing fields cause 422 — re-run market_search if needed.", "canonical": false}, {"id": "market_ask", "description": "Natural-language shopping. Examples: 'buy milk', 'repeat last purchase', 'compare rice'.", "canonical": false}, {"id": "market_basket", "description": "Compare total basket cost across retailers. Pass items with name and qty. Returns per-store totals and cheapest retailer. LATAM differentiator — 41 verified retailers across 8 countries.", "canonical": false}, {"id": "market_cart", "description": "View current cart with products, quantities, prices, and total.", "canonical": false}, {"id": "market_cart_update", "description": "Change item quantity in cart. Use quantity=0 to remove (replaces market_cart_remove in PR2).", "canonical": false}, {"id": "market_checkout", "description": "Pay for cart via CLI Market (Yape/Plin/PayPal) — creates internal order, not checkout on retailer sites. Requires Pro tier for live charge. payment_method: yape, plin, paypal, tarjeta. See GET /v1/capabilities.", "canonical": false}, {"id": "market_compare", "description": "Compare prices for one query across retailers side-by-side. Use when the user asks for cheapest option or cross-store comparison. Set country (e.g. PE) or store to avoid timeouts.", "canonical": false}, {"id": "market_login", "description": "Authenticate in CLI Market. Call before cart, checkout, or orders. Returns access + refresh tokens (access default 90d, refresh 365d) persisted locally. On 401 with expired access, CLI auto-calls POST /auth/refresh; agents may re-login or refresh.", "canonical": false}, {"id": "market_orders", "description": "Order history. Set reorder_last=true to repeat the last order.", "canonical": false}, {"id": "market_search", "description": "Search products across 41 verified retailers across 8 countries. Returns JSON with product_id, name, price, store_key (required for market_add), store, and line. Filter by line or store ID. Prefer this over scraping.", "canonical": false}], "intel": [{"id": "market_intel_brief", "description": "One-call intelligence narrative: shelf signals, macro gap vs official CPI, composite scores, and moat confidence. Replaces indicators + analytics + enrichment reads.", "canonical": true}, {"id": "market_export", "description": "Export data moat as CSV or JSON. Requires starter tier or above.", "canonical": false}, {"id": "market_inflation", "description": "Shelf inflation from the data moat: price deltas and average inflation. Filter by country or line.", "canonical": false}, {"id": "market_inflation_report", "description": "Inflation Intelligence — where is price pressure increasing? Returns pressure level (stable/rising/rising_fast/falling/above_official) from internal shelf inflation and macro CPI gap.", "canonical": false}, {"id": "market_price_risk", "description": "Price Risk Intelligence — which categories are becoming volatile? Returns risk level (low/moderate/high) with supporting signals from price dispersion, promo intensity, and staple momentum.", "canonical": false}, {"id": "market_procurement_signal", "description": "Procurement Intelligence — when should I buy? Returns buy_now/monitor/wait signal from basket stress, search momentum, and staple price trends.", "canonical": false}, {"id": "market_scores", "description": "Composite moat scores: retail_aggression, price_fairness, basket_stress, data_confidence, macro_alignment.", "canonical": false}, {"id": "market_stats", "description": "Data moat health: total prices, active stores, tracked products, last refresh.", "canonical": false}, {"id": "market_trending", "description": "Products with largest price movement in the last 7 days.", "canonical": false}], "account": [{"id": "market_price_alerts", "description": "Price alerts: query drops or configure threshold notifications for a product.", "canonical": true}, {"id": "market_favorites", "description": "Manage favorite products: list, add, or remove. Omit action for list.", "canonical": false}, {"id": "market_preferences", "description": "User preferences from purchase history: favorite stores, total spent.", "canonical": false}, {"id": "market_subscription", "description": "Current subscription plan: tier, rate limits, available API keys.", "canonical": false}, {"id": "market_whoami", "description": "Verify identity: username and subscription tier for the authenticated user.", "canonical": false}]},
  indicatorsCount: 44,
  goldenLinkagePct: 99.6,
  enrichmentSourcesLabel: "OFF · Wikimedia · Open-Meteo · World Bank · IMF · Eurostat · BCB",
  pricesVerifiedLabel: "61,000+",
  pricesRefreshHours: 4,
  pypiPackageName: "cli-market-world",
  pypiUrl: "https://pypi.org/project/cli-market-world/",
  pepyProjectUrl: "https://pepy.tech/projects/cli-market-world",
  pepyBadgeUrl: "https://img.shields.io/badge/PyPI%20downloads-39k-00d75f?logo=pypi",
  pypiDownloads: 39241,
  // Note: pepyBadgeUrl is a custom consolidated badge (legacy + core + world).
  // The live hero "PYPI DOWNLOADS" comes from /analytics/pypi (also consolidated).
  pipInstallCmd: "pip install cli-market-world",
  packageVersion: "1.9.41",
  ogImageUrl: "/og.png",
  license: "MIT",
  paymentsLabel: "PayPal (USD) · Yape · Plin · Mercado Pago (soles)",
  businessLines: 6,
  retailersPhraseEn: "81 retailers, 41 verified active",
  retailersPhraseEs: "81 retailers, 41 verificados activos",
  platformsPhraseEn: "4 platforms (VTEX · Shopify · Magento · WooCommerce)",
  platformsPhraseEs: "4 plataformas (VTEX · Shopify · Magento · WooCommerce)",
  headerEn: "CLI Market \u2014 Commerce infrastructure for AI agents.\n81 retailers across 4 platforms (VTEX \u00b7 Shopify \u00b7 Magento \u00b7 WooCommerce), 41 verified live.\n8 countries. 27 MCP tools. 61,000+ verified shelf prices, normalized per kg/L, refreshed every 4h.\nOne pip install. One API. Zero scraping. MIT.",
  headerEs: "CLI Market \u2014 Infraestructura de comercio para agentes de IA.\n81 retailers en 4 plataformas (VTEX \u00b7 Shopify \u00b7 Magento \u00b7 WooCommerce), 41 verificados y activos.\n8 pa\u00edses. 27 herramientas MCP. 61,000+ precios reales de g\u00f3ndola, normalizados por kg/L, actualizados cada 4h.\nUn pip install. Una API. Cero scraping. MIT.",
  shopifyBrands: ["Adidas", "Allbirds", "Alo Yoga", "Brooklinen", "Casper", "ColourPop", "Fenty Beauty", "Glossier", "Gymshark", "Kylie Cosmetics", "Magic Mind", "Nomad", "On Running", "Parachute", "Privalia BR"],
  seoDescription: "Commerce API for AI agents. 27 MCP tools, 81 retailers, 41 verified active. 8 countries. 61,000+ verified shelf prices refreshed every 4 hours. Normalized per kg/L, quality-filtered. pip install cli-market-world.",
  serverDescription: "Commerce for AI agents. 27 MCP tools. 81 retailers (41 verified), 8 countries, 4 platforms.",
} as const;
