// AUTO-GENERATED — do not edit. Run: python3 ops/sync_market_stats.py

export const MARKET_STATS = {
  retailersDefined: 68,
  retailersVerified: 38,
  platforms: 4,
  platformVtex: 44,
  platformShopify: 15,
  platformMagento: 7,
  platformWooCommerce: 2,
  woocommerceStores: ["Nuna Org\u00e1nica", "Xray Chipped PE"],
  countries: 8,
  countryCodes: ['AR', 'BR', 'CL', 'CO', 'FR', 'IT', 'MX', 'PE'],
  mcpTools: 43,
  indicatorsCount: 34,
  enrichmentSourcesLabel: "OFF · Wikimedia · Open-Meteo · World Bank · IMF · Eurostat · BCB",
  pricesVerifiedLabel: "49,000+",
  pricesRefreshHours: 4,
  packageVersion: "1.9.2",
  license: "MIT",
  paymentsLabel: "PayPal · Mercado Pago · QR (Yape/Plin)",
  businessLines: 6,
  retailersPhraseEn: "68 retailers, 38 verified active",
  retailersPhraseEs: "68 retailers, 38 verificados activos",
  platformsPhraseEn: "4 platforms (VTEX · Shopify · Magento · WooCommerce)",
  platformsPhraseEs: "4 plataformas (VTEX · Shopify · Magento · WooCommerce)",
  headerEn: "CLI Market \u2014 Commerce infrastructure for AI agents.\n68 retailers across 4 platforms (VTEX \u00b7 Shopify \u00b7 Magento \u00b7 WooCommerce), 38 verified live.\n8 countries. 43 MCP tools. 49,000+ verified shelf prices, normalized per kg/L, refreshed every 4h.\nOne pip install. One API. Zero scraping. MIT.",
  headerEs: "CLI Market \u2014 Infraestructura de comercio para agentes de IA.\n68 retailers en 4 plataformas (VTEX \u00b7 Shopify \u00b7 Magento \u00b7 WooCommerce), 38 verificados y activos.\n8 pa\u00edses. 43 herramientas MCP. 49,000+ precios reales de g\u00f3ndola, normalizados por kg/L, actualizados cada 4h.\nUn pip install. Una API. Cero scraping. MIT.",
  shopifyBrands: ["Adidas", "Allbirds", "Alo Yoga", "Brooklinen", "Casper", "ColourPop", "Fenty Beauty", "Glossier", "Gymshark", "Kylie Cosmetics", "Magic Mind", "Nomad", "On Running", "Parachute", "Privalia BR"],
  seoDescription: "Commerce API for AI agents. 43 MCP tools, 68 retailers, 38 verified active. 8 countries. 49,000+ verified shelf prices refreshed every 4 hours. Normalized per kg/L, quality-filtered. pip install cli-market.",
  serverDescription: "Commerce for AI agents. 43 MCP tools. 68 retailers (38 verified), 8 countries, 4 platforms.",
} as const;
